atlassian-labs/compiled

src/ts-transformer/css-prop/__tests__/index.test.tsx
src/ts-transformer/css-prop/visitors/visit-jsx-element-with-css-prop.tsx
src/ts-transformer/utils/template-literal-to-css.tsx

This adds support for transforming a template string literal that contains an object of style values

feat(css-prop): adds support for objects in template literals

---

.vscode/launch.json
jest.config.js
package.json

Add VSCode config to allow for easier step debugging through jest tests. Moves jest config to dedicated file in order to enable this, previously encountered an exception about missing configuration.

chore: add vscode debug config for jest

---

src/ts-transformer/css-prop/__tests__/index.test.tsx
src/ts-transformer/css-prop/visitors/visit-jsx-element-with-css-prop.tsx
src/ts-transformer/utils/ast-node.tsx
src/ts-transformer/utils/expression-operators.tsx

Allows the use of the classname prop 
Classes created from the CSS prop will be interpolated along with the classnames provided by the user.

feat: support className prop when using css prop

---

packages/jest/src/index.tsx
packages/jest/src/matchers.tsx
packages/ts-transform/src/styled-component/__tests__/index.test.tsx
packages/ts-transform/src/styled-component/visitors/visit-styled-component.tsx
packages/ts-transform/src/utils/extract-css-var-from-arrow-function.tsx

fix(styled): always pass the entire expression from a styled function

---

README.md
examples/css-prop-dynamic-object.tsx
examples/css-prop-static-object.tsx
packages/babel-plugin/src/__tests__/index.test.tsx
packages/css-in-js/src/index.tsx
packages/css-in-js/src/jsx/__tests__/index.test.tsx
packages/css-in-js/src/jsx/index.tsx
packages/css-in-js/src/jsx/types.tsx
packages/css-in-js/src/utils/error.tsx
packages/css-in-js/tsconfig.json
packages/ts-transform/src/__tests__/index.test.tsx
packages/ts-transform/src/class-names/index.tsx
packages/ts-transform/src/css-prop/__tests__/index.test.tsx
packages/ts-transform/src/css-prop/index.tsx
packages/ts-transform/src/styled-component/index.tsx
packages/ts-transform/src/utils/ast-node.tsx
packages/ts-transform/src/utils/visit-source-file-ensure-style-import.tsx

Removes need for jsx pragma.
Instead of using jsx import with jsx pragma `/** @jsx jsx */` - import compiled `import '@compiled/css-in-js'` and `css` prop will be enabled.
A new feature will be added later to remove the need for importing compiled at all - probably under a `useCssProp` config option.
Closes #87 #88.

BREAKING: Removes need for jsx pragma

---

packages/babel-plugin/src/__tests__/index.test.tsx
packages/ts-transform/src/__tests__/index.test.tsx
packages/ts-transform/src/constants.tsx

CSS hash now doesn't use the same prefix as emotion. Closes #131
Previous generated css hash — `.css-xxxx {}`
Now — `.cc-xxxx {}`

Generated css name should not collide with emotion - fixes #131

---

packages/css-in-js/package.json
packages/css-in-js/src/class-names/__tests__/index.test.tsx
packages/css-in-js/src/class-names/index.tsx
packages/css-in-js/src/index.tsx
packages/css-in-js/src/jsx/__tests__/index.test.tsx
packages/css-in-js/src/styled/__tests__/index.test.tsx
packages/css-in-js/src/styled/index.tsx
packages/css-in-js/src/types.tsx
yarn.lock

Selector typing fix

---

packages/jest/src/__tests__/matchers.test.tsx
packages/jest/src/matchers.tsx

Closes: #120 
Styles coming from multiple sources are added to the head as separate style elements to the head.
This PR adds support for multiple style elements and class names. If we are seeking properties from two separate sources (css prop and styled api) the matcher is now able to pick it up. 
Bonus: we're now able to output all mounted css properties in the error message.

refactor: jest matcher now supports multiple style tags

---

packages/ts-transform/src/css-prop/__tests__/index.test.tsx
packages/ts-transform/src/utils/template-literal-to-css.tsx

- Add support to use `calc` property in css-prop
- FIX: Usage of suffix in literals with object properties (`marginLeft: ${obj.prop}rem`)
- FIX: This change magically fixed a dormant bug where when more than one prop was used in BinaryExpression code paths, only the dynamic property was picked in the css
Closes #129

Support calc property; FIX: Object property with suffix;

---

.storybook/preview-head.html
examples/class-names-dynamic-object.tsx
packages/ts-transform/package.json
packages/ts-transform/src/__tests__/index.test.tsx
packages/ts-transform/src/class-names/index.tsx
packages/ts-transform/src/class-names/visitors/visit-class-names-jsx-element.tsx
packages/ts-transform/src/css-prop/index.tsx
packages/ts-transform/src/css-prop/visitors/visit-jsx-element-with-css-prop.tsx
packages/ts-transform/src/styled-component/__tests__/index.test.tsx
packages/ts-transform/src/styled-component/index.tsx
packages/ts-transform/src/styled-component/visitors/visit-styled-component.tsx
packages/ts-transform/src/types.tsx
packages/ts-transform/src/utils/create-jsx-element.tsx
packages/ts-transform/src/utils/source-maps.tsx
yarn.lock

to run locally
```
git clone git@github.com:atlassian-labs/compiled-css-in-js.git
cd compiled-css-in-js
git checkout source-maps
yarn
yarn start
```
then look at sourcemaps through storybook. you'll see generated inline sourcemaps in the head inside the inline `style` elements (in the story iframe).
---
closes #118 
so i mean i got some names showing up in dev tools. thats cool.
now when clicking on the link tho it still goes into inline. im not sure if type checking on/off is going to affect things. needs more testing.
also need to figure out if i need to link my css generated source maps with my javascript ones.. im missing something need to read up more about sourcemaps heh.
TODO:

feat: sourcemap support

---

packages/ts-transform/src/class-names/__tests__/index.test.tsx
packages/ts-transform/src/css-prop/__tests__/index.test.tsx
packages/ts-transform/src/utils/__tests__/string-iterpolations.test.tsx
packages/ts-transform/src/utils/__tests__/template-literal-to-css.test.tsx
packages/ts-transform/src/utils/array.tsx
packages/ts-transform/src/utils/string-interpolations.tsx
packages/ts-transform/src/utils/template-literal-to-css.tsx

Closes #130 
TODO
```
linear-gradient(45deg, ${N30} 25%, transparent 25%),
linear-gradient(-45deg, ${N30} 25%, transparent 25%),
linear-gradient(45deg, transparent 75%, ${N30} 75%),
linear-gradient(-45deg, transparent 75%, ${N30} 75%);
```

fix: fixes string literal interpolations being buggy

---

packages/jest/package.json
packages/jest/src/__tests__/matchers.test.tsx
packages/jest/src/index.tsx
packages/jest/src/matchers.tsx
packages/jest/src/types.tsx
yarn.lock

Fixes #138. Let me know if this approach looks okay.

feat: add support to assert styles on states (hover, active) and media queries

---

README.md

Link to consuming transformers section of ts-transform handbook was borked.

chore-fix: broken link in docs

---

packages/babel-plugin/src/__tests__/index.test.tsx
packages/css-in-js/src/__tests__/browser.test.tsx
packages/css-in-js/src/__tests__/ssr.test.tsx
packages/css-in-js/src/class-names/__tests__/index.test.tsx
packages/css-in-js/src/jsx/__tests__/index.test.tsx
packages/css-in-js/src/styled/__tests__/index.test.tsx
packages/style/src/__tests__/style-ssr.test.tsx
packages/style/src/__tests__/style.test.tsx
packages/ts-transform/src/__tests__/index.test.tsx
packages/ts-transform/src/class-names/__tests__/index.test.tsx
packages/ts-transform/src/css-prop/__tests__/index.test.tsx
packages/ts-transform/src/styled-component/__tests__/index.test.tsx
test/global.d.ts

Using configuration suggested by `jest-extended`.
https://github.com/jest-community/jest-extended#typescript
Fixes #176.

chore: configure global types for jest

---

packages/ts-transform/src/css-prop/__tests__/index.test.tsx
packages/ts-transform/src/types.tsx
packages/ts-transform/src/utils/ast-node.tsx
packages/ts-transform/src/utils/collect-declarations.tsx
packages/ts-transform/src/utils/evalulate-function.tsx
packages/ts-transform/src/utils/template-literal-to-css.tsx

`collectDeclarations` returns undefined for the const variable which throws in the generation of CSS.
Add a failing test. Blocks #178 and fixes #186

fix: destructured variable used inside string template

---

packages/babel-plugin/src/__tests__/index.test.tsx
packages/css-in-js/src/__tests__/ssr.test.tsx
packages/ts-transform/src/__tests__/index.test.tsx
packages/ts-transform/src/constants.tsx
packages/ts-transform/src/css-prop/__tests__/index.test.tsx
packages/ts-transform/src/styled-component/__tests__/index.test.tsx
packages/ts-transform/src/utils/visit-source-file-ensure-style-import.tsx

PR for #103 
Remaining issues with this PR (failing tests): 
- *css-in-js_1 is undefined*: Failing tests in css-in-js package, running that test-suite gives us a few errors about `css-in-js_1` being undefined. Looks like the common-js bundle transpiles the exports from @compiled/style down to `style_1`, I've made changes in ts-transform constants to account for this, but for reasons I do not know the css-in-js test suite still fails (do i need to run a fresh build?)
- *dangling semi-colons for removed nodes* , in this implementation we're inserting a sibling node via `visit-source-file-ensure-style-import`. on subsequent invocations of this fn, we remove the `compiled-css-in-js` import if there are no more namedImports. Oddly removals after an insertion of a sibling node via `[newNode, …

replace css in js imports with style imports

---

packages/ts-transform/src/class-names/__tests__/index.test.tsx
packages/ts-transform/src/styled-component/__tests__/index.test.tsx
packages/ts-transform/src/utils/css-transform.tsx
packages/ts-transform/src/utils/evalulate-function.tsx
packages/ts-transform/src/utils/string-interpolations.tsx
packages/ts-transform/src/utils/template-literal-to-css.tsx

197 fix styled expressions

---

packages/ts-transform/src/class-names/__tests__/index.test.tsx
packages/ts-transform/src/css-prop/__tests__/index.test.tsx
packages/ts-transform/src/styled-component/__tests__/index.test.tsx
packages/ts-transform/src/utils/expression-operators.tsx
packages/ts-transform/src/utils/template-literal-to-css.tsx

fix: short circuits css variable expressions to an empty string that have a prefix or suffix

---

packages/babel-plugin/src/__tests__/index.test.tsx
packages/babel-plugin/src/index.tsx
packages/babel-plugin/src/styled/__tests__/index.test.tsx

Closes #241 
Built on what you did @lol-russo but simplified it a lot. The basic premise is "does `React` exist somewhere in the scope - yes? Do nothing. No? Add it.

fix: imports react at the end of the transformation if its missing

---

packages/babel-plugin/package.json
packages/babel-plugin/src/css-prop/index.tsx
packages/babel-plugin/src/styled/__tests__/index.test.tsx
packages/babel-plugin/src/styled/index.tsx
packages/babel-plugin/src/utils/css-builders.tsx

Closes #246 
So this was mostly already implemented in CSS prop - I did a bit of refactoring to move the logic to `css-builder`.

feat: adds support for composing styles to styled api

---

packages/babel-plugin/src/__tests__/index.test.tsx
packages/babel-plugin/src/__tests__/module-imports.test.tsx
packages/babel-plugin/src/css-prop/__tests__/behaviour.test.tsx
packages/babel-plugin/src/index.tsx
packages/babel-plugin/src/styled/__tests__/behaviour.test.tsx
packages/babel-plugin/src/utils/ast-builders.tsx
packages/core/src/index.tsx
packages/runtime/src/__tests__/ax.test.tsx
packages/runtime/src/ax.tsx
packages/runtime/src/index.tsx

Adds the ax runtime. This still works without the atomic CSS implementation - examples still work as expected.

Add ax runtime

---

packages/css/package.json
packages/css/src/plugins/__tests__/atomicify-rules.test.tsx
packages/css/src/plugins/atomicify-rules.tsx
packages/css/tsconfig.json

Look at tests for example input and outputs.
Closes #286 
**TODO**
**TODO FOLLOW UP PR**

Atomic post css plugin

---

examples/module-traversal.tsx
packages/babel-plugin/src/__tests__/expression-evaluation.test.tsx
packages/babel-plugin/src/__tests__/module-traversal.test.tsx
packages/babel-plugin/src/utils/ast.tsx
packages/babel-plugin/src/utils/css-builders.tsx
packages/babel-plugin/src/utils/evaluate-expression.tsx

This closes #283 
- add variable declaration object destructuring support
- will work for referenced identifiers too
- will work across different modules
- fallback to variable if it can't be resolved
- refactor #resolveBindingNode to accept reference name instead of binding.
It will get binding by reference name now and resolves its node

feat: add object destructuring support

---

packages/css/src/plugins/__tests__/atomicify-rules.test.tsx
packages/css/src/plugins/__tests__/parent-orphaned-pseudos.test.tsx
packages/css/src/plugins/atomicify-rules.tsx
packages/css/src/plugins/parent-orphaned-pseudos.tsx
packages/css/src/utils/__tests__/css-transform.test.tsx

Previously  when re-parenting dangling pseudos who already had a nested selector - it would incorrectly double up the selectors.
```
&& > * {
margin-bottom: 1rem;
&:last-child {
margin-bottom: 0;
}
}
```
Would end up transforming to:
```diff
&& > * {
margin-bottom: 1rem;
+  &&:last-child
-  &:last-child {
margin-bottom: 0;
}
}
```
The code to generate a double selector was also not working:
```
.hash& > * { // <-- second & not replaced
margin-bottom: 1rem;
&:last-child {
margin-bottom: 0;
}
}
```

fix: fixes doubling up nesting selector

---

packages/babel-plugin/src/__tests__/index.test.tsx
packages/babel-plugin/src/__tests__/module-imports.test.tsx
packages/babel-plugin/src/__tests__/rule-hoisting.test.tsx
packages/babel-plugin/src/css-prop/__tests__/behaviour.test.tsx
packages/babel-plugin/src/css-prop/__tests__/object-literal.test.tsx
packages/babel-plugin/src/styled/__tests__/behaviour.test.tsx
packages/core/src/__tests__/browser.test.tsx
packages/core/src/__tests__/ssr.test.tsx
packages/css/src/plugins/__tests__/atomicify-rules.test.tsx
packages/css/src/plugins/__tests__/parent-orphaned-pseudos.test.tsx
packages/css/src/plugins/atomicify-rules.tsx
packages/css/src/plugins/parent-orphaned-pseudos.tsx
packages/css/src/utils/__tests__/css-transform.test.tsx

Previously this would break:
```
[data-hello-world]& {
display: block;
}
```
This fixes the implementation of the atomic plugin and dangling psuedos. Have a look at their tests to see further.

fix: fixes nesting selector behaviour across plugins

---

packages/babel-plugin/src/__tests__/expression-evaluation.test.tsx
packages/babel-plugin/src/class-names/__tests__/object-literal.test.tsx
packages/babel-plugin/src/css-prop/__tests__/behaviour.test.tsx
packages/babel-plugin/src/css-prop/__tests__/object-literal.test.tsx
packages/babel-plugin/src/css-prop/__tests__/string-literal.test.tsx
packages/babel-plugin/src/styled/__tests__/behaviour.test.tsx
packages/babel-plugin/src/styled/__tests__/object-literal.test.tsx
packages/babel-plugin/src/styled/__tests__/string-literal.test.tsx
packages/babel-plugin/src/utils/css-builders.tsx
packages/css/src/utils/__tests__/string-iterpolations.test.tsx

This ends up producing smaller bundlers because `var` isn't needed anymore.
**Before**
```css
--var-1As3op: blue;
```
**After**
Prefixed with an underscore because `--1` isn't a valid CSS variable name.
```css
--_1As3op: blue;
```

chore: simplify css var name

---

packages/babel-plugin/src/css-prop/__tests__/behaviour.test.tsx
packages/babel-plugin/src/css-prop/index.tsx

fix: stops class name creation when css is empty

---

package.json
packages/runtime/src/__tests__/ax.test.tsx
packages/runtime/src/ax.tsx
packages/runtime/src/index.tsx

Initially I had an implementation that did `join(' ').split(' ')` which allowed me to get the size down to `50B` but it was 30% slower than ax in master.
This PR has similar perf to ax in master.

chore: reduce ax bundlesize

---

babel.config.js
packages/babel-plugin/package.json
packages/core/babel-plugin/README.md
packages/core/babel-plugin/package.json
packages/core/package.json
packages/core/src/babel-plugin.tsx
packages/core/tsconfig.json
packages/css/package.json
packages/jest/package.json
packages/runtime/package.json
packages/utils/package.json

I wanted to do this via the `exports` field in package.json but it wouldn't work for me, so I did it the old school way. This also adds back `README.md` to packages in npm.
**Before**
```
npm i @compiled/core @compiled/babel-plugin
```
```js
module.exports = {
plugins: [['@compiled/babel-plugin'],
};
```
**After**
```
npm i @compiled/core
```
```js
module.exports = {
plugins: [['@compiled/core/babel-plugin']],
};
```
The CLA bot seems to be having problems..

feat: expose babel plugin through core to simplify consumption experience

---

packages/babel-plugin/src/__tests__/expression-evaluation.test.tsx
packages/babel-plugin/src/utils/ast.tsx
packages/babel-plugin/src/utils/evaluate-expression.tsx

We are not supporting complex `MemberExpression` object as of now. Only `Identifier` and `CallExpression` are supported as explained below:
1. Member expression `foo.bar.baz` will return the `foo` identifier along with `originalBindingType` as `Identifier`.
2. Member expression with function call `foo().bar.baz` will return the `foo` identifier along with `originalBindingType` as `CallExpression`.

fix: add null check when unhandled

---

packages/runtime/src/__tests__/__snapshots__/provider.test.tsx.snap
packages/runtime/src/__tests__/provider.test.tsx
packages/runtime/src/provider/provider-browser.tsx
packages/runtime/src/provider/provider-server.tsx

Updated the `provider-browser` and `provider-server` files to use the `isNodeEnvironment` check as per the discussion here - https://github.com/atlassian-labs/compiled/issues/353
Closes #353

browser/server providers now use isNodeEnvironment

---

packages/babel-plugin/src/class-names/__tests__/behaviour.test.tsx
packages/babel-plugin/src/class-names/index.tsx

This closes #378 
@madou: Is this that simple? We are now just checking inner scope. And that will be children function expression.

fix(classnames): check if style is coming from inner scope only

---

examples/class-names-static.tsx
examples/styled-static-object.tsx
packages/babel-plugin/src/class-names/index.tsx
packages/babel-plugin/src/styled/__tests__/behaviour.test.tsx
packages/babel-plugin/src/styled/index.tsx
packages/babel-plugin/src/utils/ast.tsx
packages/babel-plugin/src/utils/css-builders.tsx
packages/react/src/class-names/__tests__/index.test.tsx
packages/react/src/class-names/index.tsx
packages/react/src/styled/__tests__/index.test.tsx
packages/react/src/styled/index.tsx

This PR enables support for multiple args in the styled and ClassNames apis:
```js
styled.div(
{ color: 'red' },
` font-size: 20 `,
[{ backgroundColor: 'blue', padding: 10 }]
);
<ClassNames>
{({ css }) => (
<div
className={css({ fontSize: 20 }, `color: blue;`, [{ padding: 20 }], {
backgroundColor: 'red',
})}>
hello world
</div>
)}
</ClassNames>
```
Needed to update types and a little bit of the CSS builder, but for the most part no major architecture changes were needed.
Closes #352
**TODO**

feat: CSS multi args

---

packages/react/src/codemods/codemods-helpers.tsx
packages/react/src/codemods/emotion-to-compiled/__tests__/emotion-to-compiled.test.tsx
packages/react/src/codemods/emotion-to-compiled/emotion-to-compiled.tsx
packages/react/src/codemods/styled-components-to-compiled/__tests__/styled-components-to-compiled.test.tsx

The [recipe](https://github.com/facebook/jscodeshift/blob/master/recipes/retain-first-comment.md) mentioned in jscodeshift docs was only working for top level node paths.
This fix ensures they (comments) will get restored even when transformed node paths lies in between the statements.

fix(codemod): restore comments attached to transformed node paths

---

packages/react/src/codemods/codemods-helpers.tsx
packages/react/src/codemods/emotion-to-compiled/__tests__/emotion-to-compiled.test.tsx

I also realized we might want to add TODOs for unsupported APIs (`css` mixin for example). Maybe later.

chore: updates codemod todo

---

examples/default-css-variables.tsx
packages/babel-plugin/src/class-names/__tests__/object-literal.test.tsx
packages/babel-plugin/src/class-names/__tests__/string-literal.test.tsx
packages/babel-plugin/src/css-prop/__tests__/object-literal.test.tsx
packages/babel-plugin/src/css-prop/__tests__/string-literal.test.tsx
packages/babel-plugin/src/styled/__tests__/behaviour.test.tsx
packages/babel-plugin/src/styled/__tests__/object-literal.test.tsx
packages/babel-plugin/src/styled/__tests__/string-literal.test.tsx
packages/babel-plugin/src/utils/css-builders.tsx

This introduces a regression which means `undefined` can show up. We need a more holistic approach when it comes to getting rid of dynamic values that have a suffix/prefix.
For now - this means `undefinedpx` will appear. But at least `0` values can work again. I'll create a follow up ticket to look at fixing this properly.
Closes #402.
Follow up: https://github.com/atlassian-labs/compiled/issues/346

fix: reverts fallback dynamic css decl value

---

packages/react/src/codemods/codemods-helpers.tsx
packages/react/src/codemods/constants.tsx
packages/react/src/codemods/emotion-to-compiled/__tests__/emotion-to-compiled.test.tsx
packages/react/src/codemods/emotion-to-compiled/emotion-to-compiled.tsx
packages/react/src/codemods/styled-components-to-compiled/__tests__/styled-components-to-compiled.test.tsx
packages/react/src/codemods/styled-components-to-compiled/styled-components-to-compiled.tsx

@madou: Just go through the test case once. Added TODO's for `ClassNames` props so that consumers can easily replace them. Also added logic for adding TODO's for missing `styled-components` api's. Did some cleanup too 😅

Classnames codemod

---

examples/styled-interpolation-function-behavior.tsx
packages/babel-plugin/src/styled/__tests__/behaviour.test.tsx
packages/babel-plugin/src/styled/__tests__/string-literal.test.tsx
packages/css/src/utils/__tests__/string-iterpolations.test.tsx
packages/css/src/utils/css-property.tsx
packages/css/src/utils/string-interpolations.tsx
packages/react/src/styled/index.tsx
packages/react/src/types.tsx

This PR simplifies the interpolation handling by making more assumptions, and handling only things that would actually happen. Obviously invalid suffix/prefixes and the like are now unsupported.
Closes https://github.com/atlassian-labs/compiled/issues/413 
Closes https://github.com/atlassian-labs/compiled/issues/345

fix: simplify interpolation handling

---

package.json
packages/babel-plugin/src/utils/ast.tsx
packages/cli/src/isRunningInTsNode.tsx
packages/jest/src/matchers.tsx
packages/react/src/codemods/emotion-to-compiled/__tests__/emotion-to-compiled.test.tsx
packages/react/src/codemods/styled-components-to-compiled/__tests__/styled-components-to-compiled.test.tsx
packages/react/src/styled/__tests__/index.test.tsx
packages/react/src/styled/index.tsx
packages/utils/src/array.tsx
yarn.lock

When we did #349 we didn't upgrade typescript - so the examples were type erroring (but didn't break builds because it didn't typecheck during storybook build).
This upgrades TS to 4.1 to add in the new jsx behaviour.

chore: bumps typescript

---

packages/react/babel-plugin/package.json
packages/react/package.json

Closes #501 
Closes #482 
Based on this: https://nodejs.org/api/packages.html#packages_conditional_exports
Exporting different versions based on the import type of the package. Fixes this issue: https://github.com/atlassian-labs/compiled/issues/501

conditional export from the main package for cjs and esm

---

README.md
babel.config.js
examples/ssr/.babelrc
packages/react/babel-plugin/README.md
packages/react/babel-plugin/package.json
packages/react/package.json
packages/react/src/babel-plugin.tsx
packages/react/tsconfig.json
test/test-imports.js

**BREAKING CHANGE**
Removes babel plugin entrypoint from the react package. This will be a minor version bump (in our case, breaking because we are `v0.x.x`.
Closes #493 
Closes #484
**TODO**

BREAKING CHANGE: removes babel plugin from react pkg

---

.github/workflows/test.yml
examples/packages/webpack/src/app.js
examples/packages/webpack/src/component.tsx
examples/packages/webpack/src/index.js
examples/packages/webpack/webpack.config.js
package.json
packages/babel-plugin/src/transform.tsx

This ensures when parsing code it will use the local babel config - meaning TypeScript and Flow work.

fix: fixes transform parsing not using local config

---

.changeset/chatty-yaks-act.md
packages/babel-plugin/src/__tests__/expression-evaluation.test.tsx
packages/babel-plugin/src/utils/css-builders.tsx

This PR adds a support of computed properties static evaluation in object styles. Consider following example:
```javascript
import { styled } from '@compiled/react';
import React from 'react';
const media = '@media screen'
const obj = { [media]: { color: 'blue' } };
const Span = styled.span(obj);
function Component() {
return (
<Span />
);
};
```
Current implementation transpiles to something like this:
```javascript
import { forwardRef } from "react";
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import React from "react";
const _ = "._40rh13q2 media{color:blue}";
const media = "@media screen";
const obj = { [media]: { color: "blue" } };
const Span = forwardRef(({ as: C = "span", style, ...props }, ref) => (
<CC>
<CS>{[_]}</CS>
<C
{...props}
style={style}
ref={ref} …
```

Eval a computed object property in object styles

---

.changeset/stale-badgers-exercise.md
packages/react/src/runtime/sheet.tsx

Usage of `::placeholder` pseudo element throws the error in production when it gets prefixed:
```
DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule '._1idr12ax::-moz-placeholder{color:red}'.
```
After some research I found that Chrome specifically throws an exception on `insertRule` with prefixed pseudo elements. The easiest way to fix is to add try/catch block. For example, [Emotion](https://github.com/emotion-js/emotion/blob/f3c51e8aca287170e43110bee2e4527eacfcada4/packages/sheet/src/index.js#L137) handles the exception similarly. They even have a comment for `::placeholder` pseudo element and `:read-write` selector.
Reproduction: [Codesandbox](https://codesandbox.io/s/competent-bush-dcnoi?file=/pages/index.js) (development).
Demo: …

Catch unhandled exception on inserting rules with prefixed selectors

---

.changeset/red-kids-agree.md
packages/react/src/css/index.tsx

Add support of array additional parameters to css function.
The bug: 
```
const colors = { blue: () => 'blue' };
return (
<div
css={css`
/*Expected 1 arguments, but got 2.*/
background-color: ${colors.blue()};
color: #00f;      `}>
I&m blue
</div>
);
```
[Link](https://codesandbox.io/s/distracted-morning-ihd3h?file=/pages/index.tsx) to sandbox with the problem
[Proof to the solution on StackOverflow](https://stackoverflow.com/questions/49442210/template-interpolation-in-function-argument-results-in-ts2554expected-1-argumen)

feat(css function): add support of additional parameters

---

package.json
packages/babel-plugin-strip-runtime/package.json
packages/babel-plugin/package.json
packages/cli/package.json
packages/css/package.json
packages/jest/package.json
packages/parcel-transformer/package.json
packages/react/package.json
packages/tsconfig.options.json
packages/utils/package.json
packages/webpack-loader/package.json

The `package.json` files and `tsconfig.json` files are hard to scan when they are not sorted alphabetically. This set of changes sorts both sets of files, removes a redundant tsconfig option (`noImplicitAny`), and adds in a `prettier` script so that prettier can be run directly outside of commits and IDE setups.
* Sort package.json with sort-package-json
* Sort tsconfig.json alphabetically
* Add prettier script
* Remove noImplicitAny in favour of strict

Update package.json and tsconfig.json files

---

.changeset/tame-frogs-impress.md
packages/babel-plugin/package.json
packages/babel-plugin/src/__tests__/css-builder.test.tsx
packages/babel-plugin/src/__tests__/test-utils.tsx
packages/babel-plugin/src/utils/evaluate-expression.tsx

* Patch `@compiled/babel-plugin`
* Update the logic in `evaluateExpression`, so that the `ownPath` is set on a new meta object. This ensures that the correct expression is generated in the style prop, when an identifier is shadowed by a function argument.
* Create generic `transform` test utility, that will later be used for the `keyframes` API
* Add test case to `css-builders`
* Add `prettier` as a dev dependency, for the test utility

Fix identifiers shadowed by a function argument

---

package.json

Simple change so that we build both esm and cjs when developing with storybooks. This resolves inconsistencies when developing as some cjs imports are used and hence bork the dev loop with weird errors.

Build esm and cjs in storybook

---

.changeset/long-chefs-matter.md
examples/stories/css-prop-static-object.tsx
examples/stories/styled-static-object.tsx
packages/babel-plugin/src/css-prop/__tests__/behaviour.test.tsx
packages/babel-plugin/src/css-prop/__tests__/object-literal.test.tsx
packages/babel-plugin/src/utils/ast-builders.tsx

Fixes #802 
Simple change to add a key prop to generated React elements. This will suppress the React warning and remove the performance bug where React will always trigger re-rendering for children components ([per react docs](https://reactjs.org/docs/lists-and-keys.html)).

Fix missing key prop on generated React elements

---

.changeset/cold-toes-perform.md
examples/stories/conditional-rules-styled.tsx
packages/babel-plugin/src/styled/__tests__/behaviour.test.tsx
packages/babel-plugin/src/utils/css-builders.tsx

Resolves #871 
This PR changes the behaviour of ternary conditionals to not apply falsy path styles by default, instead making both paths into logical CSS items. This behaviour only works for situations like:
```
${() => ABTest() ? 'color: blue' : 'color: red'};
```
As the style property is the same on both paths can be overridden with the truthy path style. However when styles on both paths don't match up. For example:
```
${() => ABTest() ? 'font-weight: bold' : css`font-size: 20px; color: red;`};
```
Then we get unwanted styles for the falsy path.

Fix ternary condition applying all styles when taking truthy path

---

.changeset/calm-chairs-juggle.md
packages/cli/package.json

Simple PR to move codemod package to a dependency for CLI. This should allow `npx @compiled/cli` usage without having to install a peer dependency.

Add codemods package to cli to allow npx usage

---

.changeset/dull-mangos-whisper.md
examples/stories/css-prop-static-object.tsx
packages/babel-plugin/src/constants.tsx
packages/babel-plugin/src/css-prop/__tests__/behaviour.test.tsx
packages/babel-plugin/src/css-prop/index.tsx
packages/babel-plugin/src/utils/ast.tsx
packages/babel-plugin/src/utils/comments.ts

Usages like the following do not work:
```
import { css as cssSC } from "styled-components";
import { css as cssCompiled } from "@compiled/react";
const stylesSC = cssSC`
color: red;
`;
const stylesCompiled = cssCompiled`
color: blue;
`;
<>
<div css={stylesSC}>Red text</div>
<div css={stylesCompiled}>Blue text</div>
</>;
```
This is because Compiled cannot tell that `stylesSC` is defined with styled-components. To allow usages to opt-out, we should add a comment directive to allow the Compiled babel plugin to ignore certain props. e.g.
```
{isCompiledEnabled()
? <div css={{ color: 'red' }} />
// @compiled-disable-next-line transform-css-prop
: <div css={{ color: 'blue' }} />
}
```
This PR introduces `// @compiled-disable-next-line transform-css-prop` and `// @compiled-disable …

Add disable directives for css prop

---

.changeset/curvy-wasps-shake.md
.flowconfig
packages/react/src/styled/index.js.flow
scripts/flow-types.sh

Our tests did not catch this issue that occurred in Jira, as we had a different `.flowconfig`. Simple patch using `sed` to allow compatibility. 
The issue is with:
```
const x = styled.div`
...
`;
```
Throws the error:
```
Cannot call `styled.div` because inexact  object type [1] is incompatible with exact  object type [2].Flow(incompatible-exact)
react-dom.js(252, 8): [1] object type
index.js.flow(34, 26): [2] object type
```

Patch inexact type causing compatibility issues and update flowconfig

---

package.json
yarn.lock

* Remove references to `test/dead-code-elimination` as it not longer exists
* Remove `workspaces-run` dependency
* Use `find` to remove `tsbuildinfo` files

Simplify clean script

---

.changeset/small-swans-approve.md
packages/babel-plugin/src/__fixtures__/mixins/objects.js
packages/babel-plugin/src/__tests__/module-traversal.test.tsx
packages/babel-plugin/src/utils/ast.tsx
packages/babel-plugin/src/utils/evaluate-expression.tsx
packages/babel-plugin/src/utils/export-traversers.tsx

Resolves #630
Allows styles to be statically evaluated when using:
- Namespace imports - `import * as theme from 'theme';`
- Export specifiers - `export { colors };`
Does not address current issues where:
- Member expressions breaks early when identifiers and call expressions are used mid chain
- Member expressions assume parent path is same throughout the chain
Future work will be done to support:
- Nested namespace imports
- Deconstruction from namespace imports

Support namespace imports & export specifiers

---

.eslintrc.js
examples/packages/parcel/src/index.js
examples/packages/ssr/src/client.js
examples/packages/ssr/src/server.js
examples/packages/webpack/src/app.js
examples/packages/webpack/webpack.config.js
package.json

* Fix eslint violations
* Target `js` and `jsx` files in root `eslint` script
* Update eslint config to share common rules in the first override, and rely on override merging for applying additional rules

Lint js and jsx files

---

.changeset/pretty-starfishes-protect.md
packages/eslint-plugin/src/rules/jsx-pragma/__tests__/rule.test.tsx
packages/eslint-plugin/src/rules/jsx-pragma/index.tsx
packages/eslint-plugin/src/utils/ast-to-string.tsx

This pull request fixes a use case not initially considered in the lint rule - removing the default import of the React package when the fixer moves to the automatic pragma.

fix: fixes jsx-pragma rule to update react imports

---

.changeset/chilly-rats-design.md
packages/react/src/css/__tests__/index.test.tsx
packages/react/src/css/index.tsx

This pull request fixes the `css` function call to allow passing in psuedo declarations.

fix: updates css func object types

---

.changeset/eleven-geckos-grow.md
.changeset/pink-apples-appear.md
.changeset/rare-pillows-warn.md
.changeset/selfish-hounds-do.md
packages/babel-plugin-strip-runtime/package.json
packages/babel-plugin/package.json
packages/cli/package.json
packages/codemods/package.json
packages/css/package.json
packages/eslint-plugin/package.json
packages/eslint-plugin/src/rules/jsx-pragma/index.tsx
packages/eslint-plugin/src/rules/no-emotion-css/README.md
packages/eslint-plugin/src/rules/no-emotion-css/index.tsx
packages/jest/package.json
packages/parcel-transformer/package.json
packages/react/package.json
packages/react/src/class-names/index.tsx
packages/react/src/css/index.tsx
packages/react/src/jsx/jsx-local-namespace.tsx
packages/react/src/keyframes/index.tsx
packages/react/src/styled/index.tsx
packages/utils/package.json
packages/webpack-loader/package.json

This pull request:
- updates the jsdoc descriptions for the `@compiled/react` package 
- removes redundant files in `files` field in pkg json in most packages
- updates homepage in pkg json for most packages
- updates the type signature of the class names component style prop
- adds url to the lint rules

Update pkg jsdoc/json/rule

---

.changeset/silly-ducks-study.md
package.json
packages/css/package.json
yarn.lock

Forcing upgrades to `css-what` and `nth-check` to remove vulnerabilities.
We'll be able to remove this once we finish upgrading Parcel in #842 and postcss in #946.

Resolve css-what to 5.1.0 and nth-check to 2.0.1 to resolve vulnerabilities

---

renovate.json

I think the reason renovate isn't working with changesets currently is the grouping applied. I'm moving the changeset task to run on every commit as the script works in this scenario anyway.

Move changeset config to run for each PR

---

.changeset/lazy-roses-wonder.md
packages/css/package.json
yarn.lock

Another whack at resolving the VULN tickets. The theory is the package.json is getting picked up in the `@compiled/css` and but not the root of the repo.

Resolve css-what and nth-check in @compiled/css

---

.yarnrc

This file may be related to the release job failing on master. It doesn't appear to be working on my machine anymore, so we may as well remove it.

Remove .yarnrc config

---

.changeset/witty-adults-hug.md
examples/parcel/src/ui/typescript.tsx
examples/parcel/tsconfig.json

Parcel does not type check by default so we need to ensure typescript does this for us.

Add config to typecheck parcel example

---

.changeset/clean-humans-sparkle.md
.eslintrc.js
fixtures/module-a/package.json
package.json
packages/babel-plugin/package.json
packages/babel-plugin/src/__fixtures__/mixins/reexport.js
packages/babel-plugin/src/__tests__/module-traversal.test.tsx
packages/babel-plugin/src/utils/resolve-binding.ts
packages/codemods/package.json
packages/react/package.json
packages/react/src/__tests__/browser.test.tsx
packages/react/src/__tests__/display-names.test.tsx
packages/react/src/__tests__/jest-matcher.test.tsx
packages/react/src/__tests__/ssr.test.tsx
packages/react/src/class-names/__tests__/index.test.tsx
packages/react/src/css/__tests__/index.test.tsx
packages/react/src/jsx/__tests__/jsx-pragma.test.tsx
packages/react/src/keyframes/__fixtures__/index.tsx
packages/react/src/keyframes/__tests__/index.test.tsx
packages/react/src/styled/__tests__/index.test.tsx
packages/webpack-loader/package.json
stories/module-traversal.tsx
stories/simple-function-mixins.tsx
yarn.lock

This pull request adds a new ESLint rule: `import/no-extraneous-dependencies`.
It makes a few changes to allow Compiled to work with this rule:
- Added imported extraneous packages as dependencies in relevant package.json files.
- Changed 'module-a' package to '@compiled-private/module-a' to prevent name clashes.
- Updated references to '@compiled-private/module-a'.
We then documented a workaround for issue #1010: https://github.com/atlassian-labs/compiled/issues/1010

Fix: Prevent usages of extraneous packages.

---

renovate.json

We're starting to get warnings from renovate with this changeset task, as it is no longer supported

Remove changeset task on renovate

---

.changeset/unlucky-pumas-rest.md
packages/webpack-loader/src/compiled-loader.tsx
packages/webpack-loader/src/extract-plugin.tsx
packages/webpack-loader/src/types.tsx
packages/webpack-loader/src/utils.tsx

When setting up the CompiledExtractPlugin (when `extract` is enabled), we set an option on the loader context to let the @compiled/webpack-loader know that everything was set up correctly. However, when the @compiled/webpack-loader is used in conjunction with the thread-loader, the CompiledExtractPlugin is set up in a different scope to where the @compiled/webpack-loader is run. This means the check to see if the plugin was set up correctly will always fail when using the thread-loader.
The approach is to modify the loader options (that are passed directly into the @compiled/webpack-loader) instead of the loader context.

Add property to loader options when the extract plugin is enabled 

---

.changeset/purple-bugs-carry.md
packages/babel-plugin/src/__fixtures__/mixins/reexport.js
packages/babel-plugin/src/__tests__/module-traversal.test.tsx
packages/babel-plugin/src/utils/resolve-binding.ts
packages/babel-plugin/src/utils/traversers/get-export.tsx

Resolves: #1087
Adds functionality to module resolution to resolve exports like:
`export { default as A, B, default as C } from 'foo';`

1087 - Handle ExportNamedDeclarations with source for resolve binding

---

.changeset/red-dots-remember.md
packages/cli/package.json
yarn.lock

Manually bump `trim-newlines` to the newest patch version.
No need to bump meow to the major version yet - lets continue to wait until node esm support is improved.

Bump trim-newlines to v3.0.1

---

security-assistant.yml

A recent change in VULN filing allows us to opt out of no/low-risk issues.

Opt-out of low risk VULNs due to recent change

---

.changeset/tricky-doors-juggle.md
packages/babel-plugin/src/styled/__tests__/behaviour.test.ts
packages/babel-plugin/src/utils/manipulate-template-literal.ts

Resolves #1155 
Fix regex to match CSS properties with more than 2 words and also support prefixes.
Examples
```
border-top-left-radius:
-webkit-clamp:
```

1155 - Update regex matching for CSS property in conditional optimization

---

.changeset/stale-fans-laugh.md
packages/webpack-loader/src/utils.ts

This PR refactors setting the plugin configured option on the compiled webpack loader and accounts for nested rules in the webpack config https://webpack.js.org/configuration/module/#nested-rules
Fixes this bug https://github.com/atlassian-labs/compiled/issues/1137

Account for nested rules in webpack config 

---

.changeset/fast-tips-hear.md
examples/parcel/.compiledcssrc
examples/parcel/.parcelrc
packages/parcel-transformer/src/index.ts

I missed this in the previous PR but we should be passing the parser plugin into the babel operations in the parcel transformer.
Also to allow this behaviour to be tested, we have to manually specify the transformers in our example configuration, so that the root babel config is not used.

Pass through babel parser plugins in parcel transformer

---

.changeset/neat-poets-tell.md
packages/babel-plugin/src/__tests__/expression-evaluation.test.ts
packages/babel-plugin/src/test-utils.ts
packages/babel-plugin/src/utils/css-builders.ts
packages/babel-plugin/src/utils/evaluate-expression.ts

Currently we cannot handle files that use `as` on expressions we want to use in compiled.
For example:
```
const style = {
backgroundColor: 'red'
} as const;
const Component = styled.div({
"input": style,
});
```

Add support for as expressions in TypeScript

---

.changeset/loud-walls-remember.md
packages/webpack-loader/src/__tests__/extract-plugin.test.ts
packages/webpack-loader/src/__tests__/test-utils.ts
packages/webpack-loader/src/extract-plugin.ts

In the CompiledExtractPlugin, we check if the asset name ends with ‘compiled-css.css’:
https://github.com/atlassian-labs/compiled/blob/master/packages/webpack-loader/src/extract-plugin.ts#L26
However, this assumption can be incorrect if the asset name is something like [name].[contenthash].css. This will cause the following optimisation (e.g. mergeDuplicateAtRules and sortAtomicStyleSheet) not happening.

Take hashed asset name into consideration when optimizing css asset

---

.changeset/ten-trees-shave.md
examples/webpack/webpack.config.js
packages/webpack-loader/src/compiled-loader.ts

The PR follows #1225.
In #1225 @JakeLane introduced two new options, `parserBabelPlugins` and `transformerBabelPlugins`. Although both two options were added to the parcel transformer, only `transformerBabelPlugins` was added to the webpack loader while `parserBabelPlugins` is missing. The PR fixes that.

fix(webpack-loader): add missing `options.parserBabelPlugins`

---

.changeset/violet-ties-cheat.md
packages/babel-plugin/src/__tests__/module-traversal.test.ts
packages/babel-plugin/src/utils/__tests__/object-property-to-string.test.ts
packages/babel-plugin/src/utils/ast.ts
packages/babel-plugin/src/utils/css-builders.ts
packages/babel-plugin/src/utils/object-property-to-string.ts

Resolves #1295
- Fixes bug where more than one import cannot be used in template literal object property key
- Support string binary operation in object property keys

1295 - Improve support for computed object property keys

---

.changeset/loud-clouds-look.md
packages/eslint-plugin/src/rules/no-emotion-css/__tests__/rule.test.ts
packages/eslint-plugin/src/rules/no-emotion-css/index.ts

Currently, the eslint rule breaks for the whole consuming project if there are module imports
```
❯ yarn lint
Oops! Something went wrong! :(
ESLint: 8.4.1
TypeError: Cannot read property 'type' of undefined
Occurred while linting /Users/mmansour/dev/product-pricing-portal-frontend/packages/nav/src/ui/styled.tsx:4
Rule: "@compiled/no-emotion-css"
at ImportDeclaration (/Users/mmansour/dev/product-pricing-portal-frontend/node_modules/@compiled/eslint-plugin/dist/rules/no-emotion-css/index.js:54:40)
at ruleErrorHandler (/Users/mmansour/dev/product-pricing-portal-frontend/node_modules/eslint/lib/linter/linter.js:1076:28)
at /Users/mmansour/dev/product-pricing-portal-frontend/node_modules/eslint/lib/linter/safe-emitter.js:45:58
at Array.forEach (<anonymous>)
at Object.emit …
```

fix(eslint-plugin): handle importing whole modules

---

.changeset/stale-parents-pretend.md
packages/eslint-plugin/package.json
packages/eslint-plugin/src/rules/no-styled-tagged-template-expression/__tests__/rule.test.ts
packages/eslint-plugin/src/test-utils.ts
packages/eslint-plugin/src/utils/create-no-tagged-template-expression-rule/index.ts
yarn.lock

This fixed the issue: `no-styled-tagged-template-expression` ESLint rule  strips out type.
Example:
```
const Foo = styled2.div<{ color: string }>`
box-shadow: 0 0 0 2px ${({ color }) => color} inset;
`;
```
Becomes:
```
const Foo = styled2.div({
boxShadow: `0 0 0 2px ${({ color }) => color} inset`,
});
```

Add Type support to no-styled-tagged-template-expression ESLint rule

---

.changeset/pink-badgers-refuse.md
packages/css/src/__tests__/transform.test.ts
packages/css/src/plugins/expand-shorthands/__tests__/flex.test.ts
packages/css/src/plugins/expand-shorthands/flex.ts

When expanding flex, 0% is used as default value for flex-basis by browsers. Although this is not what the Spec says, we'd have to make it compatible with the browser behavior.

Use 0% as default value for flex-basis

---

.changeset/twenty-wasps-care.md
packages/codemods/src/plugins/default.ts
packages/codemods/src/plugins/types.ts
packages/codemods/src/transforms/emotion-to-compiled/README.md
packages/codemods/src/transforms/emotion-to-compiled/__tests__/transformer.test.ts
packages/codemods/src/transforms/emotion-to-compiled/index.ts
packages/codemods/src/transforms/styled-components-to-compiled/README.md
packages/codemods/src/transforms/styled-components-to-compiled/__tests__/styled-components-to-compiled-imports.test.ts
packages/codemods/src/transforms/styled-components-to-compiled/index.ts
packages/codemods/src/utils/add-comment.ts
packages/codemods/src/utils/convert-to-named-import.ts
packages/codemods/src/utils/index.ts

Currently, we remove unresolved imports and add a comment explaining this. There are some imports that have no replacement so it makes more sense to preserve them, which will make code mods require less manual intervention to land changes.
We could consider still adding the comment for documentation purposes but it seemed a bit noisy to me.

Preserve unresolved imports codemod

---

.changeset/chatty-apes-film.md
packages/codemods/src/transforms/emotion-to-compiled/__tests__/transformer.test.ts
packages/codemods/src/transforms/styled-components-to-compiled/__tests__/styled-components-to-compiled-imports.test.ts
packages/codemods/src/utils/convert-to-named-import.ts

In #1343 I introduced a fix to preserve unresolved imports from emotion and styled components. This unfortunately causes issues in practice as we don't preserve the original node correctly. This change preserves the change correctly.

Preserve the original node in the codemod plugin API

---

.changeset/chilled-rocks-kick.md
packages/css/src/plugins/expand-shorthands/__tests__/flex.test.ts
packages/css/src/plugins/expand-shorthands/flex.ts
packages/css/src/plugins/expand-shorthands/utils.ts

Fixes #1350
We should expand 0 flex-basis values to 0px despite it being different in the W3 spec. This is because browsers all transform to 0px so we should match that instead.

Fix flex shorthand expansion when flex basis is 0

---

.changeset/early-crabs-appear.md
packages/eslint-plugin/src/rules/no-styled-tagged-template-expression/__tests__/rule.test.ts
packages/eslint-plugin/src/utils/create-no-tagged-template-expression-rule/generate.ts

When auto-fixing template strings into object syntax, we drop quotes if we see any. This usually works for css properties like `content` but breaks if we need to preserve the quotes, for example: `gridTemplateAreas`.

Wrap with quote instead of dropping quote on strings in eslint rule

---

.changeset/two-avocados-kick.md
package.json
packages/react/src/runtime/__tests__/ax.test.ts
packages/react/src/runtime/ax.ts

A simple bug in the `ax` logic which was breaking styles when we have a selector style declaration. This manifests by not removing classnames that should be overridden, causing a race condition on the correct style.
This is because the early exit in the `ax` function did not account for multiple css classnames in the same string.

Fix react runtime ax function returning incorrect result for selectors

---

.changeset/real-eels-fly.md
packages/react/src/runtime/is-server-environment.ts

Our isServerEnvironment check is no longer working for Atlassian SSR. We need to check for window and also add some null checks.

Fix isServerEnvironment check

---

.changeset/khaki-coats-attend.md
packages/css/src/plugins/expand-shorthands/__tests__/utils.test.ts
packages/css/src/plugins/expand-shorthands/utils.ts

We found a bug where the `outline` property was not working, as the colour `word` was not picked up correctly. It turns out this is because `transparent` isn't a named colour. We could support this case so we manually add this to our util.
Broken:
```
const Button = styled.button({
outline: '2px solid transparent',
});
```
Works:
```
const Button = styled.button({
outlineWidth: '2px',
outlineStyle: 'solid',
outlineColor: 'transparent',
});
```

Fix transparent and currentcolor not being treated as a color

---

.changeset/thirty-days-tie.md
packages/react/package.json
packages/react/src/runtime/index.ts

We added a runtime side-effect to ensure only one copy of `@compiled/react` exists in the bundle at [PR](https://github.com/atlassian-labs/compiled/pull/1437). 
However, the side-effect relies on the assumption that modules are cached once loaded. This assumption is incorrect in many cases. It will throw a runtime error if `@compiled/react/runtime` is loaded twice. 
I think the risk outweighs the benefits of this side-effect. I will remove this side-effect in this PR and explore other ways of ensuring only one `@compiled/react` in the bundle.

remove runtime side effects

---

packages/react/src/global.d.ts

We've removed runtime side-effect at this [PR](https://github.com/atlassian-labs/compiled/pull/1447/files), but forgot to remove the Type.
This PR removes the unused Type.

Remove a unused type

---

.changeset/big-walls-boil.md

Change the changeset for `@compiled/babel-plugin` in #1467 PR from patch to minor, for consistency.

Change #1467 changeset from patch to minor

---

package.json
yarn.lock

Forcibly resolve `semver` from 5.x and 6.x to 7.x

Force update semver to 7.5.3

---

.changeset/yellow-tools-sniff.md
packages/eslint-plugin/src/rules/no-css-prop-without-css-function/__tests__/rule.test.ts
packages/eslint-plugin/src/rules/no-css-prop-without-css-function/index.ts

Follow up PR to #1491 
There is a case where we should allow function parameters and imported values in the `css` attribute: when the variable is the left hand side of an AND (`&&`) expression. Consider an example like this:
```jsx
import { css } from '@compiled/react';
const styles = css(...);
const otherStyles = css(...);
const Component = ({ myBoolean }) => <MyComponent css={[myBoolean && styles, otherStyles]} />;
<Component myBoolean />
```
Compiled handles this perfectly fine because `styles` and `otherStyles` are statically evaluable, but #1491 erroneously marks `myBoolean` as problematic. This PR fixes this.

eslint plugin: Allow function parameters/imported values in edge case

---

.eslintrc.js
package.json
packages/benchmark/package.json
packages/react/package.json
packages/react/src/css/__tests__/types.test.ts
yarn.lock

This pull request installs the `expect-type` package and writes a simple test. It's a portable library with no boiler plate to have it configured.
It does not throw errors at runtime (meaning: all tests with only type assertions will always pass). It leans on the TypeScript compiler to raise errors at compile time. That means we need to make sure we're type checking tests else the tests won't actually do anything. 
We do throw the build if there are type errors in tests currently, so happy days!
```
➜  compiled git:(expect-type-assertions) yarn build
yarn run v1.22.19
$ yarn build:babel-fixture && yarn build:browser && yarn build:cjs && yarn build:esm && yarn flow-types build && yarn postbuild
$ yarn workspace @compiled/babel-component-fixture build && yarn workspace …
```

Add example type test

---

.changeset/plenty-cats-buy.md
packages/eslint-plugin/src/rules/no-invalid-css-map/index.ts
packages/eslint-plugin/src/utils/create-no-exported-rule/check-if-compiled-export.ts

Even though `getSourceCode()` is deprecated in ESLint, support for the alternative `sourceCode` was [not added until v8.40.0](packages/eslint-plugin/src/test-utils.ts) (released May 2023). We revert back to the older syntax for compatibility with ESLint v7 and older versions of v8.

Replace sourceCode with getSourceCode

---

.changeset/orange-dragons-train.md
packages/eslint-plugin/src/rules/no-css-prop-without-css-function/__tests__/rule.test.ts
packages/eslint-plugin/src/rules/no-css-prop-without-css-function/index.ts

In a situation like this:
```tsx
import { css } from '@compiled/react';
const FloatingContainer = (css) => {
const floatingContainerStyles = css({ color: 'pink' });
const cssStyles = [floatingContainerStyles, css({ color: 'blue' })];
return (
<div ref={ref} css={cssStyles} {...rest}>
{children}
</div>
);
}
```
the `no-css-prop-without-css-function` eslint rule crashes.
This results from an incorrect assumption that traversing downwards from `css={cssStyles}` into the definition of `cssStyles` and `floatingContainerStyles`, and then traversing upwards (via `node.parent.parent.parent...`), will always get back to where you started.
In fact, after traversing downwards to `floatingContainerStyles`, traversing upwards goes through the variable declaration `const cssStyles = …

Refactor no-css-prop-without-css-function, fix edge case

---

.changeset/purple-flowers-draw.md
packages/babel-plugin/src/xcss-prop/__tests__/transformation.test.ts
packages/babel-plugin/src/xcss-prop/index.ts
packages/react/src/xcss-prop/__tests__/xcss-prop.test.tsx
packages/react/src/xcss-prop/index.ts

This pull request adds a third arg to the `XCSSProp` type to declare what properties and / or pseudos should be required. It looks like this:
```ts
XCSSProp<
'color' | 'backgroundColor',
'&hover',
{ requiredProperties: 'color'; requiredPseudos: '&:hover' }
>
```
In that example `'color'` property and `'&:hover'` pseudo is required, `'backgroundColor'` is optional. Look at tests under xcss prop for more examples.
- Both `requiredProperties` and `requiredPseudos` are constrained to the values passed in the first two generic args. If you pass something that isn't valid you'll get a type error.
- Passing `never` flags you want everything to be optional.
- Passing specific string literals flags each one should be required.
While I was here I also fixed two bugs:
- fixed passing an empty inline …

XCSS prop options arg

---

.changeset/early-lions-prove.md
packages/eslint-plugin/src/configs/recommended.ts
packages/eslint-plugin/src/index.ts
packages/eslint-plugin/src/rules/no-suppress-xcss/README.md
packages/eslint-plugin/src/rules/no-suppress-xcss/__tests__/rule.test.ts
packages/eslint-plugin/src/rules/no-suppress-xcss/index.ts
packages/react/src/xcss-prop/__tests__/xcss-prop.test.tsx

This pull request adds a new lint rule `no-suppress-xcss` that marks any ts-ignore / ts-expect-errors on the preceding line as violations when used in conjunction with xcss prop.
I will be putting up small PRs over the week to complete all the lint rules we need for the xcss prop feature. The lint rules are defined here: https://github.com/atlassian-labs/compiled/pull/1533

No suppress XCSS prop lint rule

---

.changeset/wild-berries-add.md
packages/eslint-plugin/src/configs/recommended.ts
packages/eslint-plugin/src/index.ts
packages/eslint-plugin/src/rules/no-js-xcss/README.md
packages/eslint-plugin/src/rules/no-js-xcss/__tests__/rule.test.ts
packages/eslint-plugin/src/rules/no-js-xcss/index.ts

This pull request adds a new lint rule `no-js-xcss` that marks non tsx files as violations when using xcss prop.
I will be putting up small PRs over the week to complete all the lint rules we need for the xcss prop feature. The lint rules are defined here: https://github.com/atlassian-labs/compiled/pull/1533

XCSS prop no js lint

---

packages/babel-plugin/src/babel-plugin.ts
packages/babel-plugin/src/types.ts
packages/babel-plugin/src/xcss-prop/__tests__/transformation.test.ts
packages/babel-plugin/src/xcss-prop/index.ts

This pull request fixes a bug where xcss prop would collect all styles in the module instead of the ones used. In doing that we also unblock being able to use the legacy xcss prop in the same module as the new xcss prop.
- fixes collection bug
- removes migration option as it's not needed anymore

Fix XCSS prop collecting more styles than expected

---

.changeset/flat-forks-live.md
packages/babel-plugin/src/babel-plugin.ts
packages/eslint-plugin/src/rules/jsx-pragma/__tests__/rule.test.ts
packages/eslint-plugin/src/rules/jsx-pragma/index.ts
packages/eslint-plugin/src/rules/local-cx-xcss/index.ts

This pull request updates the jsx pragma rule to mark violations when passing a `className` prop an `xcss` or named xcss prop value. To resolve your define the jsx pragma. This rule exists as a DX improvement otherwise it will be confusing how to resolve the type error when passing `className` the xcss typed object.
I will be putting up small PRs over the week to complete all the lint rules we need for the xcss prop feature. The lint rules are defined here: https://github.com/atlassian-labs/compiled/pull/1533
Violation:
```jsx
<div className={xcss} />
```
Success:
```jsx
/* @jsxImportSource @compiled/react */
<div className={xcss} />
```
**TODO**

Update jsx-pragma rule to ensure it exists when using xcss prop

---

.changeset/smooth-shirts-guess.md
packages/eslint-plugin/src/rules/jsx-pragma/README.md
packages/eslint-plugin/src/rules/jsx-pragma/__tests__/rule.test.ts
packages/eslint-plugin/src/rules/jsx-pragma/index.ts
packages/eslint-plugin/src/utils/ast.ts
packages/eslint-plugin/src/utils/create-no-exported-rule/is-styled-component.ts
packages/eslint-plugin/src/utils/jsx.ts

Add two config options to the `jsx-pragma` eslint rule:
* `detectConflictWithOtherLibraries` (**true** by default): lint error if importing any Emotion libraries in the same file as Compiled imports. Compiled styled/css/jsx/etc is not compatible with Emotion's css/jsx
* `onlyRunIfImportingCompiled` (false by default): don't give a lint error for the `css` attribute if there are no Compiled imports in the file. This allows for Emotion's `css` API and Compiled's `css` API to be used in the same repo (albeit not the same file). This doesn't apply to `xcss`.
- should be no if I understand [this PR](https://github.com/atlassian-labs/compiled/pull/1533/files#diff-b40b66ef02522d9d4bab5d1e1406b62df730ada7d15aef81918b72bd748e99ad) correctly?
- Answer: no! As long as `@compiled/react` is in scope, …

Extend jsx-pragma eslint rule: detect mixing Compiled with Emotion, and only run if importing Compiled

---

.changeset/happy-cobras-fry.md
packages/eslint-plugin/src/rules/no-exported-css/index.ts
packages/eslint-plugin/src/rules/no-exported-keyframes/index.ts

Update error message for `no-exported-css` and `no-exported-keyframes` eslint rules to be a bit more descriptive and actionable.

Update no-exported-css and no-exported-keyframes error message

---

.changeset/eighty-chefs-remain.md
packages/eslint-plugin/src/rules/no-js-xcss/index.ts
packages/eslint-plugin/src/rules/no-suppress-xcss/index.ts

Fix xcss eslint rules not being compatible with eslint v7.
`filename` and `sourceCode` were added somewhere in eslint v8.40 as a replacement for the now-deprecated `getFIleName()` and `getSourceCode()`. Not everyone is using eslint v8.40 and above 🫠
cc @kylorhall-atlassian

Fix xcss eslint rules not compatible with eslint v7

---

.changeset/silly-eels-vanish.md
packages/eslint-plugin/src/rules/jsx-pragma/README.md
packages/eslint-plugin/src/rules/no-css-prop-without-css-function/README.md
packages/eslint-plugin/src/rules/no-css-prop-without-css-function/__tests__/rule.test.ts
packages/eslint-plugin/src/rules/no-css-prop-without-css-function/index.ts
packages/eslint-plugin/src/utils/ast.ts

There are some edge cases that `no-css-prop-without-css-function` didn't handle well when used in a repository with both Emotion and Compiled. This PR provides some more configuration options that get around these edge cases:
This is perfectly normal Emotion syntax:
```tsx
/** @jsx jsx */
import { jsx } from '@emotion/react';
<div css={{ color: 'blue' }} />
```
We don't want to add Compiled to a file that already has Emotion in it. `ignoreIfImported` provides a way to exclude files that use Emotion, for example we can exclude any file that imports something from `@emotion/react` and `@emotion/core`.
```tsx
import Button from '@atlaskit/button';
<Button css={{ color: 'blue' }} />
```
`@atlaskit` components still use Emotion (as of writing :eyes:), so converting `css={{ color: 'blue' }}` to …

Add `ignoreIfImported` and `excludeReactComponents` options to `no-css-prop-without-css-function` ESLint rule

---

.changeset/nasty-seas-ring.md
packages/babel-plugin/src/babel-plugin.ts
packages/babel-plugin/src/types.ts
packages/babel-plugin/src/xcss-prop/__tests__/transformation.test.ts

Fix xcss prop PR causing incompatibilities when both Emotion and Compiled are used in the same file and not the same component:
- `css` usages in a file will no longer be processed as Compiled if `xcss` is used in the same file, so long as there is not a `@compiled/react` import specified in that file.
- Add `processXcss` option to `@compiled/babel-plugin`. If `processXcss` is set to false, `xcss` usages will be ignored, and will not be processed as Compiled. Defaults to `true`.
- This is because `xcss` is still currently implemented in Atlassian Design System using Emotion
---
*Note:*
Ideally we shouldn't allow Compiled to run on the `css` prop without use of the `css` function call and `import { css } from '@compiled/react'`. I'll make a proper writeup about this idea soon.
The current …

Fix xcss prop not being compatible with Emotion

---

.changeset/young-masks-brush.md
packages/babel-plugin/src/__tests__/index.test.ts
packages/babel-plugin/src/__tests__/jsx-automatic.test.ts
packages/babel-plugin/src/__tests__/module-imports.test.ts
packages/babel-plugin/src/keyframes/__tests__/call-expression.test.ts
packages/babel-plugin/src/keyframes/__tests__/tagged-template-expression.test.ts
packages/babel-plugin/src/styled/__tests__/behaviour.test.ts
packages/babel-plugin/src/styled/__tests__/call-expression.test.ts
packages/babel-plugin/src/styled/__tests__/tagged-template-expression.test.ts
packages/babel-plugin/src/utils/build-styled-component.ts
packages/parcel-transformer/src/__tests__/transformer.parceltest.ts

- A patch was added to JFE to inform **_developers_** to _**not**_ use innerRef as it causes issues with Compiled.
- Manually added the patch due to the origin being a JavaScript file and destination being a TypeScript file.
- Updated snapshots for unit tests

Added Babel Plugin 0.19.0 Patch from JFE

---

.changeset/shy-years-wash.md
packages/eslint-plugin/src/configs/recommended.ts
packages/eslint-plugin/src/rules/no-empty-styled-expression/README.md
packages/eslint-plugin/src/rules/no-empty-styled-expression/__tests__/rule.test.ts
packages/eslint-plugin/src/rules/no-empty-styled-expression/index.ts
packages/eslint-plugin/src/rules/no-styled-tagged-template-expression/utils.ts
packages/eslint-plugin/src/utils/styled-import.ts

- Raises an error for all styled.element() calls where either an empty object argument is passed, or no argument at all.
- Wrote tests for valid/invalid cases
- Moved common utility function `isStyledImportSpecifier` to the `eslint-plugin/src/utils` folder
- Added to recommended Compiled eslint rules as a warning
- Worked on code quality with Nathan

Created ESLint rule to disallow/discourage usage of empty styled.div() calls

---

.changeset/late-hornets-confess.md
fixtures/resolver-webpack/CHANGELOG.md
fixtures/resolver-webpack/index.js
fixtures/resolver-webpack/main.js
fixtures/resolver-webpack/package.json
packages/webpack-loader/src/__fixtures__/custom-resolver.tsx
packages/webpack-loader/src/__tests__/compiled-loader.test.ts
packages/webpack-loader/src/__tests__/test-utils.ts
packages/webpack-loader/src/compiled-loader.ts
packages/webpack-loader/src/create-default-resolver.ts
packages/webpack-loader/src/types.ts

Same as https://github.com/atlassian-labs/compiled/pull/1525 but now for webpack-loader, since Jira's SSR is still on webpack :(

Support resolver module path

---

.changeset/clean-beds-laugh.md
.changeset/config.json
packages/react/src/create-strict-api/__tests__/__fixtures__/strict-api.ts

- updated `strict-api.ts` to import from local rather than `@compiled/react`
- removed changeset due to unnecessary version bump

strict-api to import from local instead of @compiled/react

---

.changeset/tasty-vans-happen.md
packages/babel-plugin/src/babel-plugin.ts
packages/babel-plugin/src/xcss-prop/__tests__/transformation.test.ts
packages/babel-plugin/src/xcss-prop/index.ts

Currently Compiled will add its runtime even if there is no direct Compiled xcss prop usage (e.g. xcss prop from ADS primitive components!).
This pull request resolves that by moving some checks around (thanks @dddlr for putting in the initial plumbing!).

Fix Compiled runtime being added unexpectedly for xcss prop usage

---

.changeset/strong-oranges-turn.md
packages/react/src/create-strict-api/__tests__/index.test.tsx
packages/react/src/create-strict-api/index.ts

This pull request fixes a missed use case introduced in #1582 or later. The change in types resulted in output type of `cssMap` from `createStrictAPI` no longer being generic, meaning "every value" was considered to be used breaking usage in XCSSProp (as all values breaks most XCSSProp declarations).
The fix is to add more tests to cover the known use cases and to bring the generic back in as an intersection type. My brain hurts to try and understand it but all the tests pass so I'm not too worried. Potentially we might be missing test cases, I'll go over more in my head just in case.

Fix XCSSProp types

---

babel.config.json
packages/react/src/create-strict-api/__tests__/__fixtures__/strict-api-recursive.ts
packages/react/src/create-strict-api/__tests__/generics.test.tsx
packages/react/src/create-strict-api/index.ts
packages/react/src/xcss-prop/index.ts

When we were instrumenting `createStrictAPI` in platform we noticed there were some unexpected type violations. I've simplified the types internally and they go away. Since no other type violations went away / came up I'm confident in this change.
Let me know what you think!

Fix unexpected type violation with XCSSProp from createStrictAPI()

---

.changeset/gorgeous-melons-sniff.md
packages/react/src/index.ts
packages/react/src/xcss-prop/index.ts

To avoid the complexity of requiring `ReturnType<typeof XCSSProp<…>>` when creating a `createStrictAPI().XCSSProp` and `props.xcss` implementation, being able to use these types in generics are helpful.
The example usage we want is:
```tsx
import { createStrictAPI, type CSSPseudos, type StrictCSSProperties, type XCSSAllProperties, type XCSSAllPseudos } from '@compiled/react';
const { XCSSProp, css, cssMap, cx } = createStrictAPI<…>();
/** Re-implementing the jsdoc */
export type StrictXCSSProp<
TAllowedProperties extends keyof StrictCSSProperties,
TAllowedPseudos extends CSSPseudos,
TRequiredProperties extends {
requiredProperties: TAllowedProperties;
requiredPseudos: TAllowedPseudos;
} = never,
> = ReturnType<
typeof XCSSProp<TAllowedProperties, TAllowedPseudos, TRequiredProperties>
>; …
```

Export `CSSPseudos, CSSProperties, StrictCSSProperties` types for a strict `XCSSProp` implementation.

---

.changeset/kind-toys-roll.md
.changeset/sour-nails-breathe.md
packages/babel-plugin/src/css-map/index.ts
packages/react/src/create-strict-api/__tests__/generics.test.tsx
packages/react/src/create-strict-api/index.ts

This pull request updates types and adds some tests for this specific use case.

Fix nested types output from createStrictAPI() being unintentionally marked as required

---

.changeset/early-peaches-sneeze.md
.storybook/.babelrc.json
packages/babel-plugin/src/types.ts
packages/css/src/__tests__/transform.test.ts
packages/css/src/plugins/__tests__/increase-specificity.test.ts
packages/css/src/plugins/atomicify-rules.ts
packages/css/src/plugins/increase-specificity.ts
packages/css/src/transform.ts

This pull request introduces a new option to Compiled for increasing the specificity of all styles generated by Compiled, without changing the class name. This enables Compiled to remain deterministic when you have styles built from two or more sources that may or may not have increased specificity turned on.
We're going to be using this for migration to XCSSProp where the platform components haven't yet been migrated to Compiled (away from Emotion). We need to ensure that styles passed through XCSSProp win over Emotion styles in a deterministic way. This was chosen over other solutions such as prepending Emotion styles to the head instead of appending as the unknown of legacy styles in Jira and beyond being unintentionally affected.
To enable set `increaseSpecificity` to true in your …

Option to increase specificity of generated styles to enable XCSSProp migration

---

.changeset/polite-timers-rescue.md
packages/babel-plugin/src/babel-plugin.ts
packages/babel-plugin/src/class-names/index.ts
packages/babel-plugin/src/styled/index.ts
packages/babel-plugin/src/types.ts
packages/babel-plugin/src/utils/is-compiled.ts
packages/react/src/create-strict-api/__tests__/mixed.test.tsx

With the introduction of the strict API and custom importSources Compiled can now be used from different imports in the same module. One use case is when migrating to the new strict API but being blocked on something, so having to fallback to the current top-level API.
To ensure a smooth ride we need to enable Compiled to work when multiple imports exist in a module. This pull request changes the internal data structure to capture the local names of all Compiled APIs.
**TODO**

Fix Compiled throwing when multiple API imports exist in the same module

---

.changeset/clever-readers-relax.md
packages/react/src/jsx/jsx-local-namespace.ts

Inspiration: https://github.com/emotion-js/emotion/pull/3048/
This pull request adds a new type to Compiled's JSX namespace to fix usage with React 18 and its new return types (undefined / string / etc).

Fix r18 JSX namespace types

---

.changeset/pink-worms-wink.md
packages/jest/src/matchers.ts

I found it difficult to debug with `toHaveCompiledCss`, particularly in the case of local css variables being resolved by jest-dom (I think that's how it works), as the error for "could not find `padding: 8px`" doesn't tell you if it was wrong or just doesn't exist.
```tsx
expect(element).toHaveCompiledCss({ paddingInlineEdit: '8px' });
```
```sh
Could not find "padding-inline-end:8px" on <a data-testid="test-link" class="css-1mufnsm">…</a> element.
```
Now this should have a a clearer error:
```tsx
Could not find "padding-inline-end:8px" on <a data-testid="test-link" class="css-1mufnsm">…</a> element.
Found similar styles:
padding-inline-end:var(--ds-space-0, 0px)
padding-inline-end:var(--ds-space-100, 8px)
```
This could go a step further and show all css properties or have a debug mode …

Add "similar" debugging to `toHaveCompiledCss`

---

.changeset/ninety-spoons-behave.md
packages/webpack-loader/src/compiled-loader.ts
packages/webpack-loader/src/types.ts

Follow-up to https://github.com/atlassian-labs/compiled/pull/1566
Make `importSources` option available through `@compiled/webpack-loader` configuration as well.

Add importSources to @compiled/webpack-loader

---

.changeset/purple-squids-switch.md
packages/eslint-plugin/src/rules/jsx-pragma/README.md
packages/eslint-plugin/src/rules/jsx-pragma/__tests__/rule.test.ts
packages/eslint-plugin/src/rules/jsx-pragma/index.ts

Currently, the `jsx-pragma` rule only supports detecting and handling `@compiled/react` to ensure the JSX pragma is there.
However, with the `createStrictAPI` from contributions by @kylorhall-atlassian and @itsdouges, we might have Compiled APIs being imported by other libraries (e.g. `@atlaskit/css`). We add an `importSources` option to specify what these additional libraries are. This option affects two other options:
* What is counted as a "Compiled import" in the `detectConflictWithOtherLibraries` option, where we detect whether Compiled imports conflict with Emotion imports
* What is counted as a "Compiled import" in the `onlyRunIfImportingCompiled` option, where we only run this rule if a Compiled import is used in the file.

Add `importSources` option to jsx-pragma rule

---

.changeset/ten-candles-own.md
packages/parcel-transformer/src/index.ts

The transformer flames out if we don't have @compiled/react in a page, this PR just allows it to bail early

Bail out early in parcel-transformer if @compiled/react is not present

---

.changeset/two-dryers-sniff.md
packages/babel-plugin/src/utils/normalize-props-usage.ts

Fixes #1629 
https://github.com/atlassian-labs/compiled/blob/9860df3850ac5023ffa93201f5648fd7c81807c5/packages/babel-plugin/src/utils/build-styled-component.ts#L80 expects a MemberExpression in order to detect what props shouldn't be forwarded to React. All other props are forwarded to React. (see this PR for more context: https://github.com/atlassian-labs/compiled/pull/1273)
However, when we handle default values in situations like these...
```
import { styled } from '@compiled/react';
const styled.div({
margin: ({ marginTop = 12 }) => marginTop,
});
```
`@compiled/babel-plugin` used the `t.identifier` function to generate the `__cmplp.marginTop` expression:
```
styled.div<{
marginTop?: string;
}>({
marginTop: __cmplp => __cmplp.marginTop ?? '24px'
})
```
The above appears correct, …

Fix Compiled props being incorrectly forwarded when default values used

---

.changeset/funny-camels-punch.md
packages/react/src/css/index.ts

This adds basic intellisense back to the CSS function. It's not exhaustive, e.g. doesn't include pseudos / media. But it's a step forward.

Fix CSS func types

---

.changeset/rare-pans-trade.md
packages/babel-plugin/src/styled/__tests__/behaviour.test.ts
packages/babel-plugin/src/utils/__tests__/normalize-props.usage.test.ts
packages/babel-plugin/src/utils/css-builders.ts

For some reason, if you passed `props => ...` directly to `styled.div` or `css()`, and the return value of the arrow function was an object, you would cause `@compiled/babel-plugin` to crash:
```tsx
import { styled } from '@compiled/react';
import React from 'react';
const Component = styled.div(props => ({
color: `${props.customColor}`,
background: props.background,
}));
```
On the other hand, wrapping the return value inside a logical expression or ternary expression would make it work perfectly fine:
```tsx
const Styles = styled.div(
(props) => (props.isEditing ? {} : { backgroundColor: props.highlightColor }),
);
```
(note the above examples exclude TypeScript type annotations for simplicity)
This PR fixes this discrepancy.
---

Fix passing props arrow function directly to styled not working

---

.changeset/tricky-poems-greet.md
packages/react/src/create-strict-api/__tests__/__fixtures__/strict-api-recursive.ts
packages/react/src/create-strict-api/__tests__/__fixtures__/strict-api.ts
packages/react/src/create-strict-api/__tests__/css-func.test.tsx
packages/react/src/create-strict-api/__tests__/generics.test.tsx
packages/react/src/create-strict-api/__tests__/index.test.tsx
packages/react/src/create-strict-api/index.ts
packages/react/src/create-strict-api/types.ts
packages/react/src/css/index.ts
packages/react/src/types.ts
packages/react/src/xcss-prop/index.ts

This pull request refactors the types in and around the `createStrictAPI()` to fix a few bugs and underlying architectural issues. To prevent scope creeping the PR I haven't implemented nested styles for the strict API (e.g. hover inside an after pseudo) which may cause for another refactor. We can tackle that at a later date.
This is to be merged before https://github.com/atlassian-labs/compiled/pull/1634 which then will build ontop of this one.
**Background**
Previously defining the schema came with a lot of redundant work. For every pseudo that you wanted to explicitly type you would have to define it, and then all of the base types again, like so:
```tsx
interface Schema {
background: 'var(--bg)';
color: 'var(--color)';
'&:hover': {
background: 'var(--bg)';
color: …
```

Refactor strict API types

---

.changeset/fair-dolphins-tie.md
.changeset/modern-eels-tie.md
packages/babel-plugin/src/css-map/process-selectors.ts
packages/babel-plugin/src/utils/css-map.ts
packages/react/src/create-strict-api/__tests__/__fixtures__/strict-api.ts
packages/react/src/create-strict-api/index.ts
packages/react/src/create-strict-api/types.ts
packages/react/src/css-map/index.ts
packages/react/src/xcss-prop/__tests__/media-query-strict.test.tsx
packages/react/src/xcss-prop/__tests__/media-query.test.tsx
packages/react/src/xcss-prop/__tests__/xcss-prop.test.tsx
packages/react/src/xcss-prop/index.ts

This pull request introduces media query support to XCSS prop, and in turn changes some internals to make it function. Read on for the individual changes to each API.
---
**cssMap changes**
The CSS map API now allows defining top level media queries. Previously you had to define them inside a `@media` object, this restriction has now been removed bringing it inline with the CSS function API.
```jsx
import { cssMap } from '@compiled/react';
const styles = cssMap({
topLevel: { '@media (min-width: 30rem)': { color: 'green' } },
nested: { '@media': { '(min-width: 30rem)': { color: 'red' } } },
});
```
Both APIs are still supported however only the top level definition will pass type checking with XCSS prop. In the future we'll remove support for the nested object.
For the strict API the …

Add media query typing to XCSS prop / createStrictAPI

---

.changeset/orange-coins-whisper.md
packages/react/src/create-strict-api/__tests__/index.test.tsx
packages/react/src/create-strict-api/index.ts
packages/react/src/xcss-prop/__tests__/xcss-prop.test.tsx
packages/react/src/xcss-prop/index.ts

During the implementation of media query types for strict / XCSS apis we came to the realization that required pseudos isn't actually useful, only ensuring the base case properties are required is. 
This pull request removes the type property.

Remove required pseudo from XCSS prop

---

.changeset/brown-apes-jam.md
packages/parcel-transformer/src/index.ts

A simple fix to check for `program` being defined, as well as some more specific checks. This appears to occur in some edge cases where the AST object is available but the value is not set.

Check for missing AST in parcel transformer

---

.changeset/dry-ghosts-brake.md
packages/babel-plugin/src/css-map/__tests__/index.test.ts
packages/babel-plugin/src/css-map/process-selectors.ts
packages/babel-plugin/src/utils/css-map.ts

I personally noticed this wasn't breaking in local development, but was blocking in CI, and given we don't have any type checking around it, I wonder if the error is of any value?
Just figured I'd drop a PR to validate if there's a reason.

Remove the invariant to fail on an empty cssMap object for easier iterative development.

---

.changeset/empty-bags-remember.md
packages/react/src/index.ts

Currently when using moduleResolutions such as `node16`, `nodenext` or `bundler` with `declaration: true` there are quite a few typescript errors present, as shown below
I created a minimum reproduction repo to demonstrate this [here](https://github.com/mitch1995/compiled-react-module-resolution-bundler/tree/master). 
**Steps to reproduce:**
1. `npx create-react-app my-app --template typescript`
2. add dependency for `@compiled/react` (0.17.0)
3. Update `tsconfig.json` to have `moduleResolution: Bundler` and `delcaration: true`
4. Create a file using imports from `@compiled/react` like `styled` and `createStrictAPI` and you will experience type errors

Add additional type exports

---

.changeset/happy-deers-wait.md
packages/babel-plugin/src/styled/__tests__/content-property.test.ts
packages/babel-plugin/src/utils/css-builders.ts

Fixes #1650, where quotes are incorrectly added around the value in situations like `content: url(...)` and `content: counter(...)`
Thanks to @mattcompiles for suggesting this approach to fixing the bug.
Based on https://github.com/vanilla-extract-css/vanilla-extract/blob/a623c1c65a543afcedb9feb30a7fe20452b99a95/packages/css/src/transformCss.ts#L266
For the curious:
* here is how Emotion handles the `content` property: https://github.com/emotion-js/emotion/blob/f4640f6a7cbe77f790e07706b287cb29342fd0ea/packages/serialize/src/index.js#L83
* Emotion throws an error if a value does not have extra quotes surrounding it and it's not a recognised CSS value (e.g. url(...), content(...), initial, none...)
* styled-components v6 *never* adds quotes around the `content` property (and I think …

Fix handling of CSS `content` property

---

.changeset/tasty-rabbits-suffer.md
packages/babel-plugin/src/__tests__/custom-import-source.test.ts
packages/babel-plugin/src/babel-plugin.ts

To make it easier to use the design system import source we're setting it as a default import source in Compiled. This means consumers don't need to configure it, they just need to turn Compiled on.

Add new default import source (@atlaskit/css)

---

.changeset/sour-parents-look.md
.changeset/tender-panthers-flow.md
packages/css/src/__tests__/transform.test.ts
packages/css/src/plugins/__tests__/increase-specificity.test.ts
packages/css/src/plugins/increase-specificity.ts
packages/jest/src/matchers.ts
packages/utils/src/increase-specificity.ts

Without this, `jsdom` (via `nswapi`) throws an error: `SyntaxError: \8 and \9 are not allowed in strict mode.`
Refer to https://github.com/dperini/nwsapi/issues/92 for the problem statement and background.
We're instead using what stylex uses for specificity as it appears to work fine with the conflicting `jsdom` config we encountered: https://github.com/facebook/stylex/blob/c9216385d40c53612848040ab4d96ff133304203/packages/stylex/src/StyleXSheet.js#L352C16-L352C28
```diff
-._u5f3ftgi:not(#\\9){padding-right:8px}
+._u5f3ftgi:not(#\\#){padding-right:8px}
```
---
Additionally, I realize the direction of adding the increasedSpecificity selector when using a `target` option was incorrect.

Replace increase specificity selector as JSDOM breaks with `#\\9`.

---

.changeset/empty-maps-retire.md
.changeset/six-rivers-carry.md
packages/babel-plugin/src/__tests__/css-builder.test.ts
packages/babel-plugin/src/utils/css-builders.ts

Fixes the parsing of custom properties (CSS variables) names in object syntax. The casing is now preserved instead of being converted to kebab case.

Fix CSS variables casing

---

.changeset/ninety-houses-bake.md
packages/babel-plugin/src/utils/traverse-expression/traverse-member-expression/traverse-access-path/evaluate-path/index.ts

The `as const` in the following code currently causes a build error in `@compiled/babel-plugin`:
```tsx
import { css } from '@compiled/react';
const something = { large: '@media screen' } as const;
const styles = css({ [something.large]: { color: 'blue' } });
```
This is a problem because `media` from `@atlaskit/primitives/responsive` uses `as const` extensively. We would like to unblock people from using `@atlaskit/primitives/responsive` in their Compiled code, when the `@atlaskit/primitives/responsive` TypeScript source code is being consumed directly in a project.

Fix 'as const' expressions causing build error

---

.changeset/tender-plants-love.md
packages/jest/src/matchers.ts
packages/react/src/__tests__/jest-matcher.test.tsx

Previously the jest matcher would always kebab case all properties. This fixes it so it bails out if the property is a custom property.

Fix jest matcher kebab-casing CSS custom properties

---

.changeset/plenty-olives-act.md
packages/react/src/index.ts

Follow up PR to PR #1617. 
This PR adds `ElementType` the global compiled JSX namespace, as right now it's only available in the automatic jsx namespace.

Add `ElementType` to the global compiled JSX namespace

---

.changeset/nine-birds-guess.md
examples/parcel/.compiledcssrc.json
examples/webpack/webpack.config.js
packages/babel-plugin/src/test-utils.ts
packages/babel-plugin/src/utils/resolve-binding.ts
packages/parcel-transformer/src/index.ts
packages/utils/src/default-parser-babel-plugins.ts
packages/utils/src/index.ts
packages/webpack-loader/src/compiled-loader.ts
yarn.lock

`babelrc: false` was passed to `transformFromAstAsync`, but not passed to `parseAsync`. Might as well make this consistent.
I also updated `caniuse` because it was giving console warnings.
---
Edit:
I've expanded the scope of the PR to set parserBabelPlugins to ['typescript', 'jsx'] by default as well, as several internal developers in the past ran into build issues due to not setting this config option in their codebases.

Add `babelrc: false` to all Babel calls, and set `parserBabelPlugins` to `typescript` and `jsx` by default

---

website/packages/docs/src/index.html
website/packages/docs/src/pages/issues-with-emotion.mdx
website/packages/docs/src/pages/media-queries-and-other-at-rules.mdx
website/packages/docs/src/pages/migrating.mdx

This is part of a week-long project to improve our external documentation.
`@emotion/core` types being incompatible with Compiled is a very common question in our internal help channel, with this being asked about across six separate occasions. In a help channel that typically gets one to two questions a week, that is a lot!
(Atlassians: see the "2024.07 - Inno Week: Improving public-facing Compiled documentation" document for more details)
I've added a new page that specifically addresses how to fix this issue. It's named "Known issues with Emotion" with the hope that (1) if we run into other issues with Emotion, we can extend the document further; and (2) in the future, we can move more internal documentation on to our external website.
Deploy link: …

Document @emotion/core types not working with Compiled

---

website/packages/docs/src/pages/api-class-names.mdx
website/packages/docs/src/pages/api-css-prop.mdx
website/packages/docs/src/pages/api-css.mdx
website/packages/docs/src/pages/api-cssmap.mdx
website/packages/docs/src/pages/api-keyframes.mdx
website/packages/docs/src/pages/api-styled.mdx
website/packages/docs/src/pages/atomic-css.mdx
website/packages/docs/src/pages/deprecated-features.mdx
website/packages/docs/src/pages/installation.mdx
website/packages/docs/src/pages/pkg-react.mdx
website/packages/docs/src/pages/writing-css.mdx
website/packages/examples/src/css-prop-conditional-rules.tsx
website/packages/examples/src/css-prop-obj.tsx
website/packages/ui/src/layout/root.tsx

Follow-up to https://github.com/atlassian-labs/compiled/pull/1687
Update most of the Compiled documentation so that it matches our current recommendations (e.g. object styles > template strings) and [the UI Styling Standard recommendations](https://atlassian.design/components/eslint-plugin-ui-styling-standard/overview).
Sections changed as part of this PR:
See the individual commits for a detailed breakdown of changes - reading commit-by commit will likely be far easier to review. Summary of most notable commits:
* Update 'Writing CSS' and 'Installation', move some sections into new 'Deprecated features' section
* Update CSS prop page and deprecated syntax page:
- move template literals to deprecated page
- discourage dynamic styles
- move outdated composition syntax to deprecated page
* …

Update most of Compiled documentation to reflect current recommendations

---

website/packages/docs/src/index.html
website/packages/docs/src/pages/atomic-css.mdx
website/packages/docs/src/pages/installation.mdx
website/packages/docs/src/pages/media-queries-and-other-at-rules.mdx
website/packages/docs/src/pages/pkg-babel-plugin-strip-runtime.mdx
website/packages/docs/src/pages/pkg-babel-plugin.mdx
website/packages/docs/src/pages/pkg-eslint-plugin.mdx
website/packages/docs/src/pages/pkg-parcel-config.mdx
website/packages/docs/src/pages/pkg-react.mdx
website/packages/docs/src/pages/pkg-webpack-loader.mdx
website/packages/landing/src/index.html
website/packages/ui/global.css
website/packages/ui/src/components/anchor.tsx
website/packages/ui/src/components/heading.tsx
website/packages/ui/src/components/mdx-components.tsx
website/packages/ui/src/components/text.tsx

Follow-up to https://github.com/atlassian-labs/compiled/pull/1687 and https://github.com/atlassian-labs/compiled/pull/1688
Click this link to see how the website looks: https://deploy-preview-1689--compiled-css-in-js.netlify.app/
Main change:
* **Update documentation for all `@compiled/` packages** so that the options listed are actually accurate
* There's a few options that aren't used anymore - I've noted them as such in the website. We may fix this in https://github.com/atlassian-labs/compiled/issues/1690 if we get time
* For options that are used in both `@compiled/babel-plugin`and `@compiled/webpack-loader` / `@compiled/parcel-*`, I've tried my best to de-duplicate them for a single source of truth
* Other issues discovered while working on this:
* …

Update documentation for all `@compiled/` packages

---

.changeset/friendly-eels-cover.md
packages/react/src/create-strict-api/__tests__/__fixtures__/strict-api.ts
packages/react/src/create-strict-api/__tests__/pass-through-xcss.test.tsx
packages/react/src/xcss-prop/index.ts

Alternative to https://github.com/atlassian-labs/compiled/pull/1696
Migrate from `ac()` which generates `AtomicGroups` classes to `ax()` which strictly generates strings (I think that's what this all does).
This is because passing `<Component xcss={cx(style, style)}>` around resulted in errors, `'cls.split is not a function'` trying to iterate over non-strings.
Previously this generated classes collected into `ac` like:
```
[
'_1bah1yb4',
undefined,
['_16jlkb7n', undefined], // from `xcss={[…]}`, not accounted for in this PR, however, not real
AtomicGroups { // from `xcss={cx(…)}`
values: Map(2) { '_1bsb' => '_1bsb1osq', '_16jl' => '_16jlkb7n' }
}
]
```
I have...

Fix the `cx()` function's class collection at runtime as it generated class instances rather than strings.

---

package.json
yarn.lock

I believe following https://github.com/atlassian-labs/compiled/pull/1677 our releases have started to fail.
Example error: https://github.com/atlassian-labs/compiled/actions/runs/10032812760/job/27725059509#step:6:26
This is because `yarn release` runs `yarn build` at the root which runs the website which has a dependency not installed via the root `yarn install` command, so this adds `workspaces-run` to the root `yarn.lock`.

Fix the broken releases following bringing the Compiled website in.

---

.changeset/sour-birds-double.md
packages/eslint-plugin/src/rules/jsx-pragma/__tests__/rule.test.ts
packages/eslint-plugin/src/rules/jsx-pragma/index.ts
packages/eslint-plugin/src/utils/jsx.ts

This allows for more scenarios where `options.importSources` is used in the `@compiled/jsx-pragma` rule so we don'd need to import `@atlaskit/css` (our typed wrapper) _and_ `@compiled/react`.
This just refactors some parts of the AST to search for all compiled-like libraries, assuming `importSources` is that.  I think this is what the original option intended to do, but it falls short in some circumstances.
---

Update `@compiled/jsx-pragma` to properly support `importSources` 

---

.changeset/hip-dolls-kneel.md
.changeset/many-schools-do.md
packages/babel-plugin/src/__tests__/custom-import-source.test.ts
packages/babel-plugin/src/__tests__/jsx-automatic.test.ts
packages/babel-plugin/src/babel-plugin.ts
packages/webpack-loader/src/__fixtures__/lib/other-css.ts
packages/webpack-loader/src/__fixtures__/non-compiled-import-source.tsx
packages/webpack-loader/src/__tests__/compiled-loader.test.ts
packages/webpack-loader/src/__tests__/test-utils.ts
packages/webpack-loader/src/compiled-loader.ts

With https://github.com/atlassian-labs/compiled/pull/1706, I missed the fact that `@compiled/babel-plugin` requires jsx to import from strictly `@compiled/react` and doesn't fully make use of `options.importSources` here either—that pull request passed in tests and one of my dev envs, but not in a real devloop.
Additionally, this configuration had to be added to `@compiled/webpack-plugin` which wraps the Babel Plugin and had a hardcoded early exit.  For context, `@compiled/parcel-plugin` already appears to have this functionality: https://github.com/atlassian-labs/compiled/blob/master/packages/parcel-transformer/src/index.ts#L94 and I believe I've manually reviewed all instances of `'@compiled/react'` being used as a string 🤞
To enable JSX pragmas from any imported `options.importSources` …

Allow an import of `jsx` from our internal `@atlaskit/css` package for babel plugin pragma resolutions.

---

examples/ssr/package.json

Pinning path-to-regexp to resolve vuln in examples

pin path-to-regexp in examples

---

.changeset/shy-bees-fly.md
package.json
packages/react/src/runtime/style-cache.tsx

Steps to replicate (inside of our internal repo).
1. Add Compiled to an `ssr.test.tsx` with the Atlassian SSR Jest library.
2. Run tests
3. :boom:
This is because our bundler for browser dist transform `isServerEnvironment()` with `false` inline, so if something in/correctly pulls `dist/browser/…` all server tests are skipped.  See: https://github.com/atlassian-labs/compiled/blob/9a15e7420c436ff959e67004b7c6f46bec08f606/packages/react/tsconfig.browser.json#L9
I don't feel these are applicable:

Protect `@compiled/react/runtime/style-cache` better in browser distributions.

---

website/packages/docs/src/pages/pkg-babel-plugin-strip-runtime.mdx
website/packages/docs/src/pages/pkg-webpack-loader.mdx
website/packages/docs/src/pages/shorthand.mdx

Updating documentation around the `sortShorthand` config as I was confused myself setting it up in a new repo.

Fixup documentation briefly for `sortShorthand`

---

.changeset/empty-pumpkins-grin.md
packages/babel-plugin/src/__tests__/index.test.ts
packages/babel-plugin/src/types.ts
packages/css/src/plugins/atomicify-rules.ts
packages/css/src/transform.ts
packages/parcel-transformer/src/types.ts
packages/webpack-loader/src/types.ts
website/packages/docs/src/pages/pkg-babel-plugin.mdx
website/packages/docs/src/pages/pkg-parcel-config.mdx
website/packages/docs/src/pages/pkg-webpack-loader.mdx

This PR introduces a new configuration prop to `@compiled/babel-plugin` named `classHashPrefix` (feel free to suggest a better alternative) that allows users to define a prefix to be added to when generating class name hashes. 
We have an internal problem in a consumer of a remote module where it has its styles messed up due to the loss of specificity once the remote module is loaded. This is because both the wrapping application and the remote module use `@compiled` and due to the way we generate the class names, both end up generating a few with the same name. 
This is the first time I ever work with a Babel plugin so I might be missing something, all feedback is appreciated. I tried to follow the code and tests to figure out where we were generating the hashes and hooked it up with the …

Add the option to provide a prefix to generated class names 

---

website/packages/docs/src/pages/css-extraction-webpack.mdx

Extend the stylesheet extraction docs to cover not only stylesheet extraction in Webpack and Parcel, but also the stylesheet extraction used for component libraries and platform packages.
As more Atlassian developers are adopting Compiled, we have gotten a few questions internally about how to set up Compiled in their own codebases.
An area of confusion is in how stylesheet extraction works and how to set it up for _component libraries_ (as opposed to Webpack / Parcel apps), which we currently do not have documentation for.
This PR clarifies the different types of stylesheet extraction, and how to set up each type.
Updating website 🆙
@kylorhall-atlassian @JakeLane @liamqma if you get the time, I would be grateful if you could double check the factual accuracy of these changes 🙏 not 100% …

Update stylesheet extraction docs

---

.changeset/witty-bags-complain.md
packages/css/src/plugins/__tests__/sort-shorthand-declarations.test.ts
packages/css/src/plugins/sort-atomic-style-sheet.ts
packages/css/src/plugins/sort-shorthand-declarations.ts
packages/css/src/sort.ts

Fix the shorthand property sorting being buggy when not using runtime mode (e.g. when using stylesheet extraction).
@kylorhall-atlassian and I noticed that `sortShorthand` wasn't actually sorting the properties as it should.
It turns out that a lot of the time in the sorting algorithm, the two properties being compared are
* not related to each other (e.g. `padding` is related to `paddingLeft`, but `padding` is not related to `borderColor`), and
* one of the properties is a longhand property that doesn't exist in `shorthandBuckets`
As a result, there are cases where the stylesheet would not be sorted _at all_, simply because the wrong nodes were being compared and so the `sortNodes` function returns `0` every time.
Fix and simplify the `sortNodes` function:
* Remove the logic of checking …

Fix shorthand sorting buggy

---

.changeset/heavy-actors-appear.md
packages/css/src/plugins/__tests__/sort-shorthand-declarations.test.ts
packages/css/src/plugins/sort-shorthand-declarations.ts
yarn.lock

Making sure sorting works across mutli-property classes.
Example: this `{-webkit-text-decoration-color:initial;text-decoration-color:initial}` currently blocks all sorting above or below it, effectively creating a new "sorting bucket" because it always returns `0` as `a` or `b`.
This doesn't get sorted:
```css
._y44v1tgl{animation:kbayob8 5s ease infinite}
._syaz1qtk{color:var(--ds-link)}
._1jmq18uv{-webkit-text-decoration-color:initial;text-decoration-color:initial}
._zulph461{gap:var(--ds-space-050)}
```
Added a test to show how this works now!
I have...

Sort shorthand across multi-properties

---

.changeset/four-beds-own.md
packages/eslint-plugin/src/configs/flat-recommended.ts
packages/eslint-plugin/src/configs/recommended.ts

Add `shorthand-property-sorting` to recommended ESLint rules, meaning that it will be turned on by default for all codebases where `@compiled/eslint-plugin` set up correctly.
After https://github.com/atlassian-labs/compiled/pull/1700 was merged in, Compiled will now sort shorthand properties to come before longhand properties at buiild-time and runtime. @zesmith2 [made a lint rule](https://github.com/atlassian-labs/compiled/pull/1714) to enforce that the order of the properties in the source code of Compiled usages matches this ordering. We've resolved all the eslint rule violations in jira and confluence (I think?), so we can just add this as a default recommended eslint rule to remove the need to configure it manually.
Some requests from me before I go:
* If someone could extend …

Add `shorthand-property-sorting` to recommended ESLint rules

---

.changeset/plenty-feet-rest.md
packages/babel-plugin-strip-runtime/src/types.ts
packages/babel-plugin/src/css-map/__tests__/at-rules-and-selectors.test.ts
packages/babel-plugin/src/keyframes/__tests__/behaviour.test.ts
packages/babel-plugin/src/styled/__tests__/behaviour.test.ts
packages/babel-plugin/src/styled/__tests__/tagged-template-expression.test.ts
packages/css/src/__tests__/transform.test.ts
packages/css/src/plugins/sort-atomic-style-sheet.ts
packages/parcel-optimizer/src/types.ts
packages/parcel-transformer-external/src/__tests__/transformer.parceltest.ts
packages/parcel-transformer/src/__tests__/transformer.parceltest.ts
packages/webpack-loader/src/__tests__/extract-plugin.test.ts
packages/webpack-loader/src/types.ts
website/packages/docs/src/pages/pkg-babel-plugin-strip-runtime.mdx
website/packages/docs/src/pages/pkg-parcel-config.mdx
website/packages/docs/src/pages/pkg-webpack-loader.mdx
website/packages/docs/src/pages/shorthand.mdx

This matches the config we have internally at Atlassian and our recommended guidance and also matches the runtime sorting/bucketing (which has no configurable opt-out).
To reduce the configuration required and opportunity for regressions due to oversight not following expected required configuration like https://atlassian.design/get-started/develop
---

Default `sortShorthand` to true (in extraction) to reduce configuration required.

---

.changeset/purple-parrots-eat.md
.github/pull_request_template.md
packages/eslint-plugin/src/rules/shorthand-property-sorting/__tests__/rule.test.ts
packages/eslint-plugin/src/rules/shorthand-property-sorting/index.ts

Fix the rule crashing when an uninitialised variable is passed to the `css` prop.
ESLint's types give an `any` type for `functionCall.defs[0].node` so this bug was not detected by type-checking 😭 
Prevent rule from crashing when run on one of our internal codebases.
---
I have...

Fix shorthand-property-sorting crashing when styles not initialised

---

.changeset/cyan-waves-rest.md
packages/babel-plugin/src/css-map/__tests__/index.test.ts
packages/babel-plugin/src/styled/__tests__/tagged-template-expression.test.ts
packages/babel-plugin/src/utils/css-builders.ts

We extract nested member expressions inside of conditional expressions.
Fixes https://github.com/atlassian-labs/compiled/issues/1750
We simply copy the direct `buildCss > MemberExpression > …` extraction into a new path through `buildCss > ConditionalExpression > extractConditionalExpression(…) > MemberExpression > …`.
…I believe this is safe and well protected, given the underlying `extractMemberExpression` code already existed!
---
I have...

Fix broken css prop ternaries when referencing `cssMap` objects.

---

.changeset/silent-geese-wonder.md
packages/babel-plugin/src/css-map/__tests__/index.test.ts
packages/babel-plugin/src/utils/css-builders.ts
packages/babel-plugin/src/utils/css-map.ts
packages/react/src/create-strict-api/__tests__/generics.test.tsx

Fixes https://github.com/atlassian-labs/compiled/issues/1642
Example of code that silently fails today, using `styles` directly:
```tsx
import { cssMap } from '@compiled/react';
const styles = cssMap({ root: { padding: 8 } });
export default () => <div css={styles} />;
```
What we expect to see instead, using `styles.root` instead:
```tsx
import { cssMap } from '@compiled/react';
const styles = cssMap({ root: { padding: 8 } });
export default () => <div css={styles.root} />;
```
---

Throw an error when compiling a `cssMap` object where we expect a `css` or nested `cssMap` object.

---

.changeset/dirty-carrots-sit.md
.changeset/silent-geese-wonder.md
packages/babel-plugin/src/babel-plugin.ts
packages/babel-plugin/src/css-map/__tests__/index.test.ts
packages/babel-plugin/src/types.ts
packages/babel-plugin/src/utils/css-builders.ts
packages/babel-plugin/src/utils/css-map.ts
packages/react/src/create-strict-api/__tests__/generics.test.tsx

Fixes https://github.com/atlassian-labs/compiled/issues/1642
Resolves two issues revolving around `cssMap` not extracting which could lead to production issues as Runtime and Extraction are handled differently with little to no testability in this area.
1. When `cssMap` is called after it's used, eg. `<div css={styles.root}>; const styles  = cssMap({ root: … });`, styles are never extracted
2. When the root `cssMap` object is passed to css, eg. `<div css={styles}>; const styles  = cssMap(…);`, styles are never extracted and this results in no typescript error — built via https://github.com/atlassian-labs/compiled/pull/1774 and merged into this branch already.
Both of these seemingly acceptable code examples passed full CI, TS, Linting, Babel, etc., but styles were simply never displayed …

Fix `@compiled/babel-plugin` to not silently skip `cssMap()` extraction in a few common edge-cases.

---

.changeset/few-camels-compare.md
packages/eslint-plugin/src/rules/shorthand-property-sorting/__tests__/rule.test.ts
packages/eslint-plugin/src/rules/shorthand-property-sorting/index.ts

Fix two edge cases:
* When using the _same properties_ across two `css` function calls through ternary operators, we should not get an ESLint violation.
```tsx
import { css } from '@compiled/react';
const oldStyles = css({
font: '...',
fontWeight: '...',
});
const newStyles = css({
font: '...',
fontWeight: '...',
});
const someCondition = true;
export const EmphasisText = ({ children }) => <span css={[someCondition ? oldStyles : newStyles]}>{children}</span>;
```
* When using the _same properties_ across two keys in a `cssMap` function call, we should not get an ESLint violation.
```tsx
import { cssMap } from '@compiled/react';
const styles = cssMap({
warning: {
borderColor: '...',
borderTop: '...',
},
debug: {
borderColor: '...',
borderTop: '...',
},
normal: {
borderColor: '...', …
```

Fix some false positives with ternary operators and cssMap

---

examples/webpack/webpack.config.js
website/packages/docs/src/pages/css-extraction-webpack.mdx

Clarify in the documentation that with Webpack stylesheet extraction, the developer needs to make sure that the `compiled-css.css` filename contains a unique hash.
Our Webpack-based production environments expect a unique hash as part of the filename path.
---
I have...

Add hash to stylesheet extraction docs

---

CONTRIBUTING.md

Clarify in the CONTRIBUTING.md page what Atlassian employees should do to meet the CLA requirement.
Several past instances where we could not find where the instructions were
---
I have...

Clarify that CLA is not needed for Atlassian employees

---

.github/workflows/visual-regression-test.yml

Bumps `actions/upload-artifcat` to version 4 following https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md (eg. no changes expected)
All builds are failing due to a blocking upstream change: https://github.com/atlassian-labs/compiled/actions/runs/13124206809/job/36617003663?pr=1792

Bump actions/upload-artifact@v4 following blocking deprecation.

---

website/packages/docs/src/pages/limitations.mdx
website/packages/docs/src/pages/migrating.mdx

Updating https://compiledcssinjs.com/ with changes noted internally:
- Fixing the "Migrating from Emotion" link as it's broken.
- The "dynamic selectors" issue isn't a runtime issue, it's generic.
- Mixing dynamic values and indirect selectors will never work (we should `throw new Error`) (https://github.com/atlassian-labs/compiled/issues/1789)
- Ternaries _should_ work now (fixed through https://github.com/atlassian-labs/compiled/issues/389 and https://github.com/atlassian-labs/compiled/issues/1750)

Update website limitations from recent fixes and findings

---

.changeset/shy-deers-exist.md
packages/css/src/plugins/__tests__/sort-at-rules.test.ts
packages/css/src/plugins/at-rules/parse-media-query.ts
packages/css/src/plugins/sort-atomic-style-sheet.ts

Update the `parseAtRule` function to ensure it only runs for media queries (what the function is designed for) and not other types of at-rules. Also update the name to clarify that it only works for media queries.
Fixes the bug where this causes Compiled to crash at build time:
```
const overlayStyles = css({
'@supports not (height: 1lh)': {
color: token('color.text'),
},
});
```
This is because the presence of `height` causes the at-rule to be treated like a media query, resulting in Compiled crashing when the at-rule doesn't use the expected syntax.
---
I have...

Fix height usages causing crash in non-media query

---

website/packages/docs/src/pages/limitations.mdx

Documents https://github.com/atlassian-labs/compiled/issues/1794 on behalf of @oleg-chibikov 
I have...

Document new limitation from #1794

---

.changeset/many-sheep-change.md
packages/babel-plugin/src/css-map/__tests__/index.test.ts
packages/babel-plugin/src/utils/css-builders.ts

Describe what change you are making here.
Give the full context for your change here.
(Optional.)
---
I have...

Not generate cache for identifier

---

.changeset/long-foxes-pay.md
packages/react/src/keyframes/__tests__/index.test.tsx
packages/react/src/keyframes/index.ts

Today, `keyframes()` doesn't work with CSS variables, eg. this doesn't work, this PR fixes the types for it.
```tsx
const animation = keyframes({
from: { '--opacity': 1 },
to: { '--opacity: 0 },
});
```
While CSS variables can be unsafe at times, there are some circumstances where this is the absolute best way to animate something, and Compiled should still protect from arbitrarily imported `[variableName]` properties regardlesss.
---

Improve the types to the `keyframes()` function to handle CSS variables.

---

.changeset/seven-falcons-build.md
packages/css/src/plugins/expand-shorthands/__tests__/flex.test.ts
packages/css/src/plugins/expand-shorthands/flex.ts

This adds more shorthand expansion logic to the `flex` shorthand parsing.
Namely, because `flex: 'inherit'` becomes `flex: 'auto'` via `flex-grow: 1; flex-shrink: 1; flex-basis: auto` which isn't what [MDN says](https://developer.mozilla.org/en-US/docs/Web/CSS/flex) and may result in bugs internally.
By adding direct keyword support and adding tests.
---

Properly handle more flex keywords in shorthand extraction.

---

.changeset/sweet-eggs-tan.md
packages/react/src/types.ts

In a `@compiled/react` cssMap style I wanted to define an `em` value for a letter spacing style. I noticed I could only use number values. This means I can only define a `px` values. With this change I'm able to define values with `em` or other units for letterspacing (and other style properties).
Opening up the type to allow values of type string allows me to use `em` and other units for style values.
In [this change](https://github.com/atlassian-labs/compiled/commit/20528e9115efbb30932f2a0215b4b550d94ac40a#diff-84f256c9526675be4ce59318afe5f494f4ef705bc836911864ff1f4f6159602dR107) `string & object` was added to fix type inference. This was probably changed from `string & {}` to `string & object` by linting. I have changed this to `string & NonNullable<unknown>` to support string values …

Type definition css properties string values fix

---

.changeset/nasty-jars-roll.md
package.json
packages/react/src/runtime/__perf__/ax.test.ts
packages/react/src/runtime/__tests__/ax.test.ts
packages/react/src/runtime/ax.ts

This change results in:
- A smaller bundle size (`362b` → `305b` using `esbuild --minify`)
- Faster runtime performance (when there is higher variance in the keys). The new variant was consistency ~60% faster on [this test case](https://jsbench.me/2nm89s22n9) [Chrome@134]
- Improved clarity of code + code paths.
📺 [I made a video about this change to step through all my thought process](https://www.youtube.com/watch?v=-wmYoQ7Ph8A)
📖 [More information on Objects vs Maps](https://www.zhenghao.io/posts/object-vs-map)

optimising ax and improving its clarity

---

.changeset/plain-windows-listen.md
packages/jest/src/matchers.ts
packages/react/src/__tests__/jest-matcher.test.tsx

Use `classList` instead of `className` in `toHaveCompiledCss`
`SVGElement` does not have a `className` property.  Additionally we are splitting a string to iterate through it, but `classList` is already iterable.
---
I have...

Fix toHaveCompiledCss crash for SVG elements

---

.changeset/lazy-bats-remain.md
.changeset/lovely-rockets-hammer.md
fixtures/babel-component-extracted/.babelrc
fixtures/babel-component-extracted/src/index.jsx
fixtures/babel-component/.babelrc
fixtures/babel-component/src/index.jsx
packages/babel-plugin/src/__tests__/module-traversal.test.ts
packages/babel-plugin/src/keyframes/__tests__/call-expression.test.ts
packages/babel-plugin/src/keyframes/__tests__/tagged-template-expression.test.ts
packages/babel-plugin/src/types.ts
packages/css/src/__tests__/transform.test.ts
packages/css/src/plugins/__tests__/flatten-multiple-selectors.test.ts
packages/css/src/plugins/flatten-multiple-selectors.ts
packages/css/src/transform.ts
packages/parcel-transformer-external/src/__tests__/transformer.parceltest.ts
packages/parcel-transformer/src/__tests__/transformer.parceltest.ts
packages/react/src/__tests__/browser.test.tsx
website/packages/docs/src/pages/pkg-babel-plugin.mdx

Flatten multiple selectors into separate rules to better deduplicate and sort styles.
```tsx
css({
'&:hover, &:focus': {
color: 'red',
},
});
```
Is transformed into the same code as this would be:
```tsx
css({
'&:hover': { color: 'red' },
'&:focus': { color: 'red' },
});
```
This will be enabled by default in a future minor release once impact is validated.
Without this, pseudo-selectors aren't sorted properly in some scenarios, eg. we always expect `&:active` to override `&:hover` styles, eg. `._1di61dty:active` not be losing to `._irr3166n:hover`, but our sorting is based off of the first selector when multiple selectors are found.
```css
._1di61dty:active {
background-color: var(--ds-background-neutral-subtle-pressed, #091e4224);
}
._1di6166n:active, ._jomr166n:focus, …
```

Allow flattening of multiple selectors into separate rules to better deduplicate and sort styles.

---

.changeset/slick-waves-punch.md
.changeset/wild-aliens-hug.md
packages/react/src/create-strict-api/__tests__/__fixtures__/strict-api-recursive.ts
packages/react/src/create-strict-api/__tests__/generics.test.tsx
packages/react/src/create-strict-api/types.ts
packages/react/src/types.ts
packages/react/src/xcss-prop/__tests__/xcss-prop.test.tsx
packages/react/src/xcss-prop/index.ts

Adding the types to the types file and copying the specific selectors from xcss 
- should we have more types here ? Are there any other flat pseudos we want? 
Allow for flattened chained pseudo-selectors, eg. `&:hover::after` in our type syntaxes. Kylor's PR https://github.com/atlassian-labs/compiled/pull/1834 allows for the nesting to occur, but sometimes a flattened selector can be cleaner for some users and I don't think it's supported with that PR 🤔 
Happy to decline if i'm misunderstanding that PR !
I have...

Allow for flattened chained pseudo-selectors, eg. `&:hover::after` in our types

---

.changeset/thin-towns-invent.md
packages/react/src/types.ts

- add a few more flattened pseudos, 
one of them was used in atlaskit -> &:visited:focus', want to avoid having more ts-expect-errors so trying to anticipate other potential combinations 
---
I have...

add more flattened pseudos to allowed types
