atlassian-labs/compiled

.github/workflows/build.yml, .github/workflows/test.yml
=> Add CI scripts

src/ts-transformer/css-prop/visitors/visit-jsx-element-with-css-prop.tsx
=> fix: unbreak ts-loader compat by avoiding node mutations

src/ts-transformer/class-names/__tests__/index.test.tsx, src/ts-transformer/class-names/index.tsx, src/ts-transformer/class-names/visitors/visit-class-names-jsx-element.tsx, src/ts-transformer/css-prop/__tests__/index.test.tsx, src/ts-transformer/css-prop/index.tsx, src/ts-transformer/css-prop/visitors/visit-jsx-element-with-css-prop.tsx, src/ts-transformer/styled-component/__tests__/index.test.tsx, src/ts-transformer/styled-component/index.tsx, src/ts-transformer/styled-component/visitors/visit-styled-component.tsx, src/ts-transformer/types.tsx, src/ts-transformer/utils/ast-node.tsx, src/ts-transformer/utils/collect-declarations.tsx, src/ts-transformer/utils/evalulate-function.tsx, src/ts-transformer/utils/object-literal-to-css.tsx, src/ts-transformer/utils/template-literal-to-css.tsx
=> feat: enables simple function declarations to be compiled

README.md
=> [Low prio] Move emoji outside of link

packages/ts-transform/src/class-names/index.tsx, packages/ts-transform/src/class-names/visitors/visit-class-names-jsx-element.tsx, packages/ts-transform/src/constants.tsx, packages/ts-transform/src/css-prop/__tests__/index.test.tsx, packages/ts-transform/src/css-prop/index.tsx, packages/ts-transform/src/css-prop/visitors/visit-jsx-element-with-css-prop.tsx, packages/ts-transform/src/styled-component/index.tsx, packages/ts-transform/src/styled-component/visitors/visit-styled-component.tsx, packages/ts-transform/src/utils/create-jsx-element.tsx, packages/ts-transform/src/utils/hash.tsx
=> Consolidate jsx creation, fix css prop style bug

packages/css-in-js/src/styled/__tests__/index.test.tsx, packages/css-in-js/src/styled/index.tsx, packages/ts-transform/src/styled-component/__tests__/index.test.tsx, packages/ts-transform/src/styled-component/index.tsx, packages/ts-transform/src/styled-component/visitors/visit-styled-component.tsx
=> feat: adds composed component support to styled api

packages/jest/src/__tests__/matchers.test.tsx, packages/jest/src/matchers.tsx
- Refactors the source code slightly
- Adds support for `.not.toHaveStyledCss`
- Adds tests 
Addresses: #123
=> Minor tweeks and fixes to the jest style matcher

packages/babel-plugin/src/__tests__/index.test.tsx, packages/ts-transform/src/__tests__/index.test.tsx, packages/ts-transform/src/utils/create-jsx-element.tsx
=> chore: remove css hash prefix

packages/css-in-js/src/styled/__tests__/index.test.tsx, packages/ts-transform/src/styled-component/__tests__/index.test.tsx, packages/ts-transform/src/styled-component/index.tsx, packages/ts-transform/src/utils/create-jsx-element.tsx
=> feat: adds display name in dev

packages/ts-transform/src/class-names/__tests__/index.test.tsx, packages/ts-transform/src/css-prop/__tests__/index.test.tsx, packages/ts-transform/src/styled-component/__tests__/index.test.tsx, packages/ts-transform/src/utils/__mocks__/hash.tsx, packages/ts-transform/src/utils/object-literal-to-css.tsx, packages/ts-transform/src/utils/template-literal-to-css.tsx
=> Dedupe interpolations

packages/ts-transform/src/css-prop/__tests__/index.test.tsx, packages/ts-transform/src/utils/create-jsx-element.tsx
=> fix: fixes css prop passing down undefined to class name

packages/ts-transform/src/utils/__tests__/css-transform.test.tsx, packages/ts-transform/src/utils/css-transform.tsx
=> fix: turns off normalize charset cssnano plugin

packages/ts-transform/src/css-prop/__tests__/index.test.tsx, packages/ts-transform/src/utils/create-jsx-element.tsx
=> fix: fixes css prop transform from passing through defined props

packages/ts-transform/src/css-prop/__tests__/index.test.tsx, packages/ts-transform/src/utils/object-literal-to-css.tsx
=> 205 fix template literal

packages/ts-transform/src/css-prop/__tests__/index.test.tsx, packages/ts-transform/src/utils/__tests__/string-iterpolations.test.tsx, packages/ts-transform/src/utils/string-interpolations.tsx
=> Fix interpolations that are delimited by spaces being picked up as suffixes 

packages/ts-transform/src/utils/__tests__/css-transform.test.tsx, packages/ts-transform/src/utils/css-transform.tsx
=> feat: honour browserslist options via config/env vars

packages/ts-transform/package.json, packages/ts-transform/src/utils/__tests__/css-transform.test.tsx, packages/ts-transform/src/utils/css-transform.tsx, packages/ts-transform/types/postcss-selector-parser.d.ts
=> chore(css-transform): replace postcss selector parsing with official library

CONTRIBUTING.md
Update CLA links in CONTRIBUTING.MD to use the new CLA system
=> updating CLA links

packages/babel-plugin/src/css-prop/__tests__/index.test.tsx, packages/babel-plugin/src/styled/__tests__/index.test.tsx, packages/babel-plugin/src/utils/ast.tsx, packages/babel-plugin/src/utils/css-builders.tsx
=> feat: adds support for inlining constant property access

examples/styled-interpolation-function-behavior.tsx, packages/babel-plugin/src/styled/__tests__/index.test.tsx, packages/babel-plugin/src/utils/ast-builders.tsx, packages/babel-plugin/src/utils/ast.tsx
=> feat: [#257] add logic for picking arrow functions body

packages/babel-plugin/src/css-prop/__tests__/index.test.tsx, packages/babel-plugin/src/index.tsx, packages/babel-plugin/src/styled/__tests__/index.test.tsx, packages/babel-plugin/src/styled/index.tsx, packages/babel-plugin/src/types.tsx
=> fix: fixes hard coded usage of styled import specifier

examples/static-evaluation.tsx, packages/babel-plugin/src/css-prop/__tests__/index.test.tsx, packages/babel-plugin/src/styled/__tests__/index.test.tsx, packages/babel-plugin/src/utils/ast.tsx, packages/babel-plugin/src/utils/css-builders.tsx
=> feat: evaluates constant expressions

examples/composing-styles-on-user-defined-components.tsx, packages/babel-plugin/src/styled/__tests__/index.test.tsx, packages/babel-plugin/src/styled/index.tsx, packages/babel-plugin/src/types.tsx, packages/babel-plugin/src/utils/ast-builders.tsx
=> Styled component composing styles onto other components

packages/babel-plugin/src/__tests__/expression-evaluation.test.tsx, packages/babel-plugin/src/utils/ast.tsx
=> fix: fixes evaluation blowing up when referencing local func args

package.json, packages/babel-plugin/src/__tests__/index.test.tsx, packages/babel-plugin/src/__tests__/module-imports.test.tsx, packages/babel-plugin/src/css-prop/__tests__/behaviour.test.tsx, packages/babel-plugin/src/styled/__tests__/behaviour.test.tsx, packages/babel-plugin/src/utils/ast-builders.tsx, packages/runtime/src/__tests__/style.test.tsx, packages/runtime/src/dev-warnings.tsx, packages/runtime/src/sheet.tsx, packages/runtime/src/style.tsx
Just smashed this out before going out haha, let me know what you think.
Closes #288
=> Replace component hashing with sheet hashing

packages/babel-plugin/src/__tests__/index.test.tsx, packages/babel-plugin/src/__tests__/module-imports.test.tsx, packages/babel-plugin/src/__tests__/rule-hoisting.test.tsx, packages/babel-plugin/src/css-prop/index.tsx, packages/babel-plugin/src/index.tsx, packages/babel-plugin/src/styled/__tests__/behaviour.test.tsx, packages/babel-plugin/src/styled/index.tsx, packages/babel-plugin/src/types.tsx, packages/babel-plugin/src/utils/ast-builders.tsx, packages/babel-plugin/src/utils/types.tsx
=> Hoist style rules to top of the module

package.json, packages/runtime/src/__tests__/ax.test.tsx, packages/runtime/src/ax.tsx
It was missing a piece of behaviour.
Adds more code - any thoughts on how to shrink it down?
=> fix: adds missing behaviour to ax func

packages/babel-plugin/src/__tests__/errors.test.tsx, packages/babel-plugin/src/__tests__/expression-evaluation.test.tsx, packages/babel-plugin/src/__tests__/index.test.tsx, packages/babel-plugin/src/__tests__/module-imports.test.tsx, packages/babel-plugin/src/__tests__/module-traversal.test.tsx, packages/babel-plugin/src/__tests__/rule-hoisting.test.tsx, packages/babel-plugin/src/class-names/__tests__/behaviour.test.tsx, packages/babel-plugin/src/class-names/__tests__/object-literal.test.tsx, packages/babel-plugin/src/class-names/__tests__/string-literal.test.tsx, packages/babel-plugin/src/css-prop/__tests__/behaviour.test.tsx, packages/babel-plugin/src/css-prop/__tests__/object-literal.test.tsx, packages/babel-plugin/src/css-prop/__tests__/string-literal.test.tsx, packages/babel-plugin/src/styled/__tests__/behaviour.test.tsx, packages/babel-plugin/src/styled/__tests__/object-literal.test.tsx, packages/babel-plugin/src/styled/__tests__/string-literal.test.tsx, packages/babel-plugin/src/utils/__tests__/cache.test.tsx, packages/babel-plugin/src/utils/ast-builders.tsx, packages/core/src/__tests__/browser.test.tsx, packages/core/src/__tests__/ssr.test.tsx, packages/core/src/jsx/__tests__/index.test.tsx, packages/core/src/styled/__tests__/index.test.tsx, packages/css/src/utils/__tests__/css-transform.test.tsx, packages/css/src/utils/css-transform.tsx, packages/jest/src/__tests__/matchers.test.tsx
This adds the atomic post css plugin into the mix, and fixes all the tests.
Closes #271
=> Wire up atomic plugin

package.json, packages/core/src/__tests__/browser.test.tsx, packages/jest/src/matchers.tsx, packages/runtime/src/__tests__/style-ssr.test.tsx, packages/runtime/src/__tests__/style.test.tsx, packages/runtime/src/is-node.tsx, packages/runtime/src/provider/index.tsx, packages/runtime/src/style.tsx, packages/runtime/tsconfig.json, yarn.lock
=> fix: refactors browser check to be a node check to enable ssr to work in jsdom environments

packages/runtime/src/is-node.tsx
From here: https://github.com/atlassian-labs/compiled/pull/314/files#r503583214
This will require consumers be running on node `> 12.x`
=> using globalThis to detect if running in node

packages/core/src/__tests__/server-side-hydrate.test.tsx
This test ensures that ssr hydration works correctly with compiled.
=> test: add ssr hydration tests

packages/core/package.json, packages/core/src/codemods/README.md, packages/core/src/codemods/codemods-helpers.tsx, packages/core/src/codemods/emotion-to-compiled/README.md, packages/core/src/codemods/emotion-to-compiled/__tests__/emotion-to-compiled.test.tsx, packages/core/src/codemods/emotion-to-compiled/emotion-to-compiled.tsx, packages/core/src/codemods/emotion-to-compiled/index.tsx, packages/core/src/codemods/styled-components-to-compiled/README.md, packages/core/src/codemods/styled-components-to-compiled/__tests__/styled-components-to-compiled.test.tsx, packages/core/src/codemods/styled-components-to-compiled/index.tsx, packages/core/src/codemods/styled-components-to-compiled/styled-components-to-compiled.tsx, yarn.lock
This closes #239 
This closes #179
=> feat: add codemod for sc and emotion

.storybook/addons.js, .storybook/config.js, .storybook/main.js, examples/benchmarks/compiled.tsx, examples/benchmarks/emotion.tsx, examples/composing-styles-on-user-defined-components.tsx, examples/css-prop-dynamic-object.tsx, examples/css-prop-static-object.tsx, examples/media-queries.tsx, examples/module-traversal.tsx, examples/simple-function-mixins.tsx, examples/static-evaluation.tsx, examples/style-buckets.tsx, examples/styled-dynamic-object.tsx, examples/styled-interpolation-function-behavior.tsx, examples/styled-static-object.tsx, package.json, yarn.lock
=> Benchmarks

packages/react/runtime/package.json
Got this while testing with jest
=> fix: runtime browser import path

packages/babel-plugin/src/__tests__/index.test.tsx, packages/cli/package.json, packages/cli/src/presets/codemods/README.md, packages/react/src/codemods/emotion-to-compiled/README.md, packages/react/src/codemods/styled-components-to-compiled/README.md
@madou: See if this PR makes sense. Make cli instructions more clear.
=> Update cli run instructions

.eslintrc.js, examples/conditional-rules.tsx, packages/babel-plugin/src/__tests__/css-builder.test.tsx, packages/babel-plugin/src/class-names/index.tsx, packages/babel-plugin/src/css-prop/__tests__/behaviour.test.tsx, packages/babel-plugin/src/css-prop/index.tsx, packages/babel-plugin/src/utils/ast-builders.tsx, packages/babel-plugin/src/utils/css-builders.tsx, packages/babel-plugin/src/utils/types.tsx, packages/jest/src/matchers.tsx
Closes #278 
**Todo**
**Out of scope**
We'll have follow up tickets for these.
- Ternary styles `isPrimary ? { color: 'red' } : { color: 'blue' }`
- Styled component support
- Template literal support
=> feat: conditional css rules for css prop

packages/babel-plugin/package.json, packages/cli/package.json, packages/css/package.json, packages/jest/package.json, packages/react/package.json, packages/utils/package.json
=> chore: corrects github url

examples/css-prop-dynamic-object.tsx, packages/css/src/plugins/__tests__/atomicify-rules.test.tsx, packages/css/src/plugins/atomicify-rules.tsx, packages/css/src/utils/__tests__/css-transform.test.tsx, packages/css/src/utils/__tests__/string-iterpolations.test.tsx, packages/css/src/utils/string-interpolations.tsx
=> fix: fixes important being including in suffix

examples/css-prop-dynamic-object.tsx, packages/css/src/utils/__tests__/string-iterpolations.test.tsx, packages/css/src/utils/string-interpolations.tsx
=> fix: fixes prefix interpolations on template literals

packages/babel-plugin/src/styled/__tests__/behaviour.test.tsx, packages/babel-plugin/src/utils/css-builders.tsx, packages/css/src/plugins/expand-shorthands/index.tsx, packages/css/src/utils/__tests__/css-transform.test.tsx
=> fix: fixes postcss autoprefixer blowing up from expanding plugin

CONTRIBUTING.md, LICENSE, README.md, packages/babel-plugin/README.md, packages/cli/README.md, packages/css/README.md, packages/jest/README.md, packages/react/README.md, packages/utils/README.md
Had some downtime so I threw this up. It updates the README and also uses the OSS template for Atlassian projects.
Don't merge until we've released.
Closes https://github.com/atlassian-labs/compiled/issues/410
=> chore: update README for library re-release

package.json, packages/react/package.json, yarn.lock
Fixing https://github.com/atlassian-labs/compiled/security/dependabot/yarn.lock/node-notifier/open
=> fix: upgrade jest to fix a security vuln

packages/cli/src/__tests__/main.test.tsx, packages/react/src/codemods/constants.tsx
=> fix: fixes cli not finding codemods

examples/conditional-rules.tsx, examples/static-evaluation.tsx, packages/react/src/jsx/__tests__/index.test.tsx, packages/react/src/types.tsx
fix #489
This is my first contribution to JavaScript library 😄 
Please give me advice about tests and Storybook. I can't find CSS Prop tests.
=> fix: Add boolean to CSS Prop type

examples/packages/module-a/index.d.ts, examples/packages/module-a/index.js, examples/simple-function-mixins.tsx, packages/babel-plugin/src/__fixtures__/mixins/objects.js, packages/babel-plugin/src/__tests__/module-traversal.test.tsx, packages/babel-plugin/src/class-names/__tests__/object-literal.test.tsx, packages/babel-plugin/src/class-names/__tests__/string-literal.test.tsx, packages/babel-plugin/src/css-prop/__tests__/object-literal.test.tsx, packages/babel-plugin/src/css-prop/__tests__/string-literal.test.tsx, packages/babel-plugin/src/styled/__tests__/object-literal.test.tsx, packages/babel-plugin/src/styled/__tests__/string-literal.test.tsx, packages/babel-plugin/src/types.tsx, packages/babel-plugin/src/utils/ast.tsx, packages/babel-plugin/src/utils/css-builders.tsx, packages/babel-plugin/src/utils/evaluate-expression.tsx, packages/react/src/styled/__tests__/index.test.tsx
This closes #341 
@madou: Did something 😅 Its working though 🎉
=> feat: functions with arguments mixin support

.changeset/proud-clouds-hang.md, packages/utils/src/error.tsx, packages/webpack-loader/package.json, packages/webpack-loader/src/__tests__/compiled-loader.test.tsx, packages/webpack-loader/src/__tests__/extract-plugin.test.tsx, packages/webpack-loader/src/__tests__/utils/webpack.tsx, packages/webpack-loader/src/compiled-loader.tsx, packages/webpack-loader/src/extract-plugin.tsx, packages/webpack-loader/src/utils/webpack.tsx, packages/webpack-loader/tsconfig.json
Closes #666 
**TODO**
**Follow up issues**
=> fix: fixes webpack extract bugs

.changeset/silver-jobs-type.md, packages/react/src/__tests__/ssr.test.tsx, packages/react/src/runtime/style.tsx
Fixes #756.
@madou I fixed my CI config, so it should be okay now. But if it's not, please let me know🙂
=> Fix html escaping

.changeset/mean-avocados-retire.md
Simple changeset to trigger new version on CLI
=> Add changeset for @compiled/cli to bump dependencies

.eslintrc.js, packages/babel-plugin-strip-runtime/src/utils/remove-style-declarations.ts, packages/babel-plugin/src/types.tsx, packages/babel-plugin/src/utils/css-builders.tsx, packages/babel-plugin/src/utils/export-traversers.tsx, packages/cli/src/presets/codemods/codemods.tsx, packages/codemods/src/codemods-helpers.tsx, packages/codemods/src/transforms/emotion-to-compiled/emotion-to-compiled.tsx, packages/codemods/src/transforms/styled-components-inner-ref-to-ref/styled-components-inner-ref-to-ref.tsx, packages/codemods/src/transforms/styled-components-to-compiled/styled-components-to-compiled.tsx, packages/css/src/plugins/expand-shorthands/types.tsx, packages/css/src/plugins/sort-at-rule-pseudos.tsx, packages/eslint-plugin/src/rules/emotion-to-compiled/__tests__/rule.test.tsx
* Add `@typescript-eslint/array-type` lint rule
* Remove unused lint rules
=> Add consistent array types

.changeset/light-owls-kick.md, packages/babel-plugin/src/styled/__tests__/behaviour.test.tsx, packages/babel-plugin/src/utils/css-builders.tsx
I'm very open to better wording in the changeset if there are any suggestions.
=> Fix ternary conditionals with template literal branches

.eslintrc.js, scripts/generate-renovate-changeset.ts
=> Fix import order issues for changset script and update eslint excludes

.changeset/yellow-lies-live.md, .github/workflows/release.yml, package.json, yarn.lock
**Note** this should cause the next master commit to release.
The master release process failed due to a recent bump. See https://github.com/changesets/changesets/releases/tag/%40changesets%2Fcli%402.18.1 for the new version.
=> Bump @changesets/cli to fix broken release

CONTRIBUTING.md
Add some small instructions on how to test with webpack 4.
=> Add instructions to CONTRIBUTING.md on how to test with webpack 4

.changeset/pink-pumpkins-exercise.md, package.json, packages/cli/package.json, packages/codemods/package.json, yarn.lock
Seems to be passing locally. Is there a better way of testing that this hasn't broken the codemods?
=> resolve unset-values to ^2.0.0 to fix vuln

.changeset/quick-points-serve.md, packages/babel-plugin/src/__tests__/expression-evaluation.test.tsx, packages/babel-plugin/src/utils/evaluate-expression.tsx
=> Prevent error being thrown when evaluating declarations

.changeset/short-cheetahs-tap.md, packages/codemods/codeshift.config.js
Hey folks 👋 
I've just added a [CodeshiftCommunity](https://www.codeshiftcommunity.com/) config because I think it's a great candidate for compiled, since you guys maintain a wrapper CLI for JSCodeshift. 
Codeshift is intended to act as a generic CLI wrapper of JSCodeshift and will allow you remove your CLI completely, if that's something you folks would rather not maintain. For now this will work in parallel to your CLI, in case you wanted to trial the library before committing to it. 
This comes with some additional goodies: 
- Codemods will automatically updated every time `compiled/codemods` is published to NPM
- Users won't have to install the `@compiled/react` to gain access to the codemods before running ([ie these instructions](https://github.com/atlassian-labs/compiled/tree/master …
=> Consider adopting CodeshiftCommunity 🚚

.changeset/itchy-turtles-boil.md, packages/codemods/package.json
To ensure codeshift.config is published to npm 😄
=> Adds codeshift.config to the npm allow list

packages/react/src/css/index.ts, yarn.lock
- Fixing the CSS type expecting a children prop
- Outdated ip dependency needs update to work with storybook
=> Update CSS type to ignore props and fix broken yarn lock dependency

.changeset/fast-books-glow.md, packages/eslint-plugin/src/rules/no-styled-tagged-template-expression/__tests__/rule.test.ts, packages/eslint-plugin/src/utils/create-no-tagged-template-expression-rule/index.ts, packages/eslint-plugin/src/utils/create-no-tagged-template-expression-rule/to-arguments.ts
This resolves https://github.com/atlassian-labs/compiled/issues/1312
=> fix breaking rule

.changeset/cool-nails-help.md, packages/babel-plugin/src/__tests__/expression-evaluation.test.ts, packages/babel-plugin/src/utils/traverse-expression/traverse-call-expression.ts
Fixes https://github.com/atlassian-labs/compiled/issues/1200
=> fix an issue of double call expression in traverseCallExpression

.changeset/seven-grapes-breathe.md, packages/eslint-plugin/src/rules/no-css-tagged-template-expression/__tests__/rule.test.ts, packages/eslint-plugin/src/rules/no-keyframes-tagged-template-expression/__tests__/rule.test.ts, packages/eslint-plugin/src/rules/no-styled-tagged-template-expression/__tests__/rule.test.ts, packages/eslint-plugin/src/utils/create-no-tagged-template-expression-rule/index.ts
Resolves https://github.com/atlassian-labs/compiled/issues/1333
=> Autofix empty tagged template expressions

.vscode/launch.json
=> Update debug configuration to use correct config filename

.changeset/forty-parrots-warn.md, packages/babel-plugin/src/utils/__tests__/normalize-props.usage.test.ts, packages/babel-plugin/src/utils/normalize-props-usage.ts
=> Support default parameters in arrow functions

.changeset/nice-pots-confess.md, packages/eslint-plugin/src/rules/no-css-prop-without-css-function/__tests__/rule.test.ts, packages/eslint-plugin/src/rules/no-css-prop-without-css-function/index.ts, packages/eslint-plugin/src/utils/ast-to-string.ts
=> Fix duplicate css import in eslint plugin

packages/eslint-plugin/src/rules/jsx-pragma/README.md
Address PR comments re: `jsx-pragma` eslint rule documentation from @itsdouges
=> Update jsx-pragma documentation

.changeset/brown-llamas-hunt.md, packages/eslint-plugin/src/index.ts
- Caused JFE/CFE "cannot find rule ___" error
=> Fixed eslint rule declaration typo

packages/eslint-plugin/src/rules/no-invalid-css-map/README.md
=> Fix typo in no-invalid-css-map README

.github/CODEOWNERS
Update code owners to remove @zerosicx 😢 so that she no longer gets pinged for every PR we make
=> Remove Hannah from code owners

packages/babel-plugin/src/__tests__/expression-evaluation.test.ts
Follow-up to https://github.com/atlassian-labs/compiled/pull/1670
=> Add test for `as const` expression in object key

packages/codemods/src/transforms/emotion-to-compiled/README.md
=> Another one, remove old codemod docs references

.github/CODEOWNERS
Update codeowners to add some members of Design System Team.
Design System Team are more active in this repo than we are 😅 
Let me know if there are other people I should add.
---
I have...
=> Update Compiled codeowners
